In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
results_path = '/content/drive/My Drive/Online MSDS/MOD C2/Political Polarization/results/'
# results_path = 'results/'

In [3]:
linear_regression_imbalanced = pd.read_csv(f"{results_path}model1_linear-model-summary_imbalanced.csv")
linear_regression_resampled = pd.read_csv(f"{results_path}model1_linear-model-summary_resampled.csv")
linear_regression_SMOTE = pd.read_csv(f"{results_path}model1_linear-model-summary_SMOTE.csv")

logistic_regression_imbalanced = pd.read_csv(f"{results_path}model4_logistic-regression-summary_imbalanced.csv")
logistic_regression_resampled = pd.read_csv(f"{results_path}model4_logistic-regression-summary_resampled.csv")
logistic_regression_SMOTE = pd.read_csv(f"{results_path}model4_logistic-regression-summary_SMOTE.csv")
logistic_regression_weighted = pd.read_csv(f"{results_path}model4_logistic-regression-summary_weighted.csv")

svm_classification_imbalanced = pd.read_csv(f"{results_path}model5_svm-classification-summary_imbalanced.csv")
svm_classification_resampled = pd.read_csv(f"{results_path}model5_svm-classification-summary_resampled.csv")
svm_classification_SMOTE = pd.read_csv(f"{results_path}model5_svm-classification-summary_SMOTE.csv")
svm_classification_weighted = pd.read_csv(f"{results_path}model5_svm-classification-summary_weighted.csv")
svm_regression_resampled = pd.read_csv(f"{results_path}model5_svm-regression-summary_resampled.csv")

dt_classification_imbalanced = pd.read_csv(f"{results_path}model6_dt-classification-summary_imbalanced.csv")
dt_classification_resampled = pd.read_csv(f"{results_path}model6_dt-classification-summary_resampled.csv")
dt_classification_SMOTE = pd.read_csv(f"{results_path}model6_dt-classification-summary_SMOTE.csv")
dt_classification_weighted = pd.read_csv(f"{results_path}model6_dt-classification-summary_weighted.csv")
dt_regression_resampled = pd.read_csv(f"{results_path}model6_dt-regression-summary_resampled.csv")

rf_classification_imbalanced = pd.read_csv(f"{results_path}model6_rf-classification-summary_imbalanced.csv")
rf_classification_resampled = pd.read_csv(f"{results_path}model6_rf-classification-summary_resampled.csv")
rf_classification_SMOTE = pd.read_csv(f"{results_path}model6_rf-classification-summary_SMOTE.csv")
rf_classification_weighted = pd.read_csv(f"{results_path}model6_rf-classification-summary_weighted.csv")
rf_regression_resampled = pd.read_csv(f"{results_path}model6_rf-regression-summary_resampled.csv")

knn_classification_imbalanced = pd.read_csv(f"{results_path}model8_knn-classification-summary_imbalanced.csv")
knn_classification_resampled = pd.read_csv(f"{results_path}model8_knn-classification-summary_resampled.csv")
knn_classification_SMOTE = pd.read_csv(f"{results_path}model8_knn-classification-summary_SMOTE.csv")
knn_regression_resampled = pd.read_csv(f"{results_path}model8_knn-regression-summary_resampled.csv")

gb_classification_imbalanced = pd.read_csv(f"{results_path}model9_gb-classification-summary-imbalanced.csv")
gb_classification_resampled = pd.read_csv(f"{results_path}model9_gb-classification-summary-resampled.csv")
gb_regression_resampled = pd.read_csv(f"{results_path}model9_gb-regression-summary-resampled.csv")

xgb_classification_imbalanced = pd.read_csv(f"{results_path}model9_gb-classification-summary-xgb-imbalanced.csv")
xgb_classification_resampled = pd.read_csv(f"{results_path}model9_gb-classification-summary-xgb-resampled.csv")
xgb_classification_weighted = pd.read_csv(f"{results_path}model9_gb-classification-summary-xgb-weighted.csv")
xgb_regression_resampled = pd.read_csv(f"{results_path}model9_gb-regression-summary-xgb-resampled.csv")

kmeans_clustering_imbalanced = pd.read_csv(f"{results_path}model10_kmeans-clustering-summary_imbalanced.csv")
kmeans_clustering_resampled = pd.read_csv(f"{results_path}model10_kmeans-clustering-summary_resampled.csv")
kmeans_clustering_SMOTE = pd.read_csv(f"{results_path}model10_kmeans-clustering-summary_SMOTE.csv")

In [4]:
linear_regression_imbalanced.head()

,Model,Dataset,RMSE,R2,Coefficients,Feature Coefficients,Balance
0,Linear Regression,Convabuse,0.330115,0.891958,{'annotator_id': np.float64(0.0211623065364701...,"{'system': np.float64(0.48385017824834126), 'e...",Imbalanced
1,Linear Regression,Dynamically Generated Hate Speech,0.338133,0.540195,"{'type': np.float64(-0.3710247267464888), 'ann...","{'original': np.float64(0.10876639976590403), ...",Imbalanced
2,Linear Regression,US Elections 2020 Hate Speech,0.310790,0.064087,"{'Trump': np.float64(-0.05392014424852679), 'B...","{'West': np.float64(0.0), 'Trump': np.float64(...",Imbalanced
3,Linear Regression,MLMA Hate Speech,0.671301,0.076915,{'shock_annotator_sentiment': np.float64(0.014...,{'sadness_annotator_sentiment': np.float64(0.0...,Imbalanced

In [5]:
linear_regression_resampled.head()

,Model,Dataset,RMSE,R2,Coefficients,Feature Coefficients,Balance
0,Linear Regression,Convabuse,6.394386e-01,0.795539,{'annotator_id': np.float64(0.0891325421479631...,"{'system': np.float64(0.6812356291906492), 'ex...",Resampled
1,Linear Regression,Dynamically Generated Hate Speech,3.349200e-01,0.551314,"{'type': np.float64(-0.37591947687307), 'annot...","{'original': np.float64(0.10320610623148284), ...",Resampled
2,Linear Regression,Online Abusive Attacks,3.541690e-13,1.000000,{'Parent tweets': np.float64(0.275934286530178...,{'High profanity parents': np.float64(22.62607...,Resampled
3,Linear Regression,US Elections 2020 Hate Speech,4.710882e-01,0.112304,"{'Trump': np.float64(-0.12802209933773415), 'B...","{'West': np.float64(0.0), 'Trump': np.float64(...",Resampled
4,Linear Regression,MLMA Hate Speech,1.023212e+00,0.162586,{'shock_annotator_sentiment': np.float64(0.013...,{'sadness_annotator_sentiment': np.float64(0.1...,Resampled

In [6]:
linear_regression_SMOTE.head()

,Model,Dataset,RMSE,R2,Coefficients,Feature Coefficients,Balance
0,Linear Regression,Convabuse,0.645283,0.791794,{'annotator_id': np.float64(0.0924749766950985...,"{'explicit': np.float64(0.45529909401421254), ...",SMOTE
1,Linear Regression,Dynamically Generated Hate Speech,0.333085,0.556217,"{'type': np.float64(-0.38253202005709663), 'an...","{'original': np.float64(0.10397921440364759), ...",SMOTE
2,Linear Regression,US Elections 2020 Hate Speech,0.466779,0.128471,"{'Trump': np.float64(-0.17322390985672034), 'B...","{'West': np.float64(0.0), 'Trump': np.float64(...",SMOTE
3,Linear Regression,MLMA Hate Speech,1.026703,0.156705,{'shock_annotator_sentiment': np.float64(0.017...,{'sadness_annotator_sentiment': np.float64(0.1...,SMOTE

In [7]:
logistic_regression_imbalanced.head()

,Dataset,Regularizer,Solver,Accuracy,F1-score,Ratio,Feature Importances,Balance,Model
0,Convabuse,l1,liblinear,0.885533,0.852027,0.0,"{'bot': 0.5777202483608284, 'generalised': 0.0...",Imbalanced,Logistic Regression
1,DGHS,l1,liblinear,0.827553,0.808568,0.0,"{'original': 3.880785596630201, 'target_groups...",Imbalanced,Logistic Regression
2,Online Abusive Attacks,l1,saga,0.812095,0.800787,0.0,"{'Toxic replies': -6.170820812897218, 'Toxic p...",Imbalanced,Logistic Regression
3,US2020HS,l1,liblinear,0.883139,0.000000,0.0,"{'West': 0.0, 'Trump': -0.5047453980305149, 'B...",Imbalanced,Logistic Regression
4,MLMA Hate Speech,l1,saga,0.596364,0.496579,0.0,"{'Not Abusive': 0.3372934904240555, 'indiffere...",Imbalanced,Logistic Regression

In [8]:
logistic_regression_resampled.head()

,Dataset,Regularizer,Solver,Accuracy,F1-score,Ratio,Feature Importances,Balance,Model
0,Convabuse,l1,saga,0.548797,0.534900,0.0,"{'bot': 0.3135946990754108, 'generalised': 0.0...",SMOTE,Logistic Regression
1,DGHS,l1,liblinear,0.836848,0.805039,0.0,"{'original': 3.8367515347660825, 'target_group...",SMOTE,Logistic Regression
2,Online Abusive Attacks,l1,saga,0.903777,0.897601,0.0,"{'index': -0.24873302012164952, 'Toxic replies...",SMOTE,Logistic Regression
3,US2020HS,l1,liblinear,0.643939,0.643939,0.0,"{'West': 0.0, 'Trump': -0.5361364908316495, 'B...",SMOTE,Logistic Regression
4,MLMA Hate Speech,l2,liblinear,0.238278,0.092972,0.0,"{'implicit': 0.0001300202623139896, 'abuse_lev...",SMOTE,Logistic Regression

In [9]:
logistic_regression_SMOTE.head()

,Dataset,Regularizer,Solver,Accuracy,F1-score,Ratio,Feature Importances,Balance,Model
0,Convabuse,l1,saga,0.544967,0.513890,0.0,"{'bot': 0.5859231731296082, 'generalised': 0.0...",SMOTE,Logistic Regression
1,DGHS,l1,liblinear,0.838416,0.807275,0.0,"{'original': 3.871260109046368, 'target_groups...",SMOTE,Logistic Regression
2,Online Abusive Attacks,l1,saga,0.903777,0.898398,0.0,"{'Toxic replies': -7.789314268739111, 'Toxic p...",SMOTE,Logistic Regression
3,US2020HS,l1,liblinear,0.648674,0.650330,0.0,"{'West': 0.0, 'Biden': -0.5157701187647922, 'T...",SMOTE,Logistic Regression
4,MLMA Hate Speech,l2,liblinear,0.575000,0.419841,0.0,"{'implicit': 0.3859362706501835, 'abuse_level'...",SMOTE,Logistic Regression

In [10]:
logistic_regression_weighted.head()

,Dataset,Regularizer,Solver,Accuracy,F1-score,Ratio,Feature Importances,Balance,Model
0,Convabuse,l1,liblinear,0.885533,0.853066,0.0,"{'bot': 0.5775275892056827, 'generalised': 0.0...",Weighted,Logistic Regression
1,DGHS,l1,liblinear,0.827553,0.808568,0.0,"{'original': 3.851019278039954, 'target_groups...",Weighted,Logistic Regression
2,Online Abusive Attacks,l1,liblinear,0.868251,0.864666,0.0,"{'Toxic replies': -16.193728095652887, 'Toxic ...",Weighted,Logistic Regression
3,US2020HS,l1,liblinear,0.646077,0.307190,0.0,"{'West': 0.0, 'Biden': -0.5153487915313094, 'T...",Weighted,Logistic Regression
4,MLMA Hate Speech,l1,liblinear,0.467857,0.459772,0.0,"{'implicit': 0.0, 'abuse_level': -0.0760710347...",Weighted,Logistic Regression

In [11]:
svm_classification_imbalanced.head()

,Dataset,Kernel,Regularization,Accuracy,F1 Score,Permutation Importances,Balance,Model
0,Convabuse,Linear,L1,0.885533,0.852027,"{'implicit': 0.035771065182829874, 'explicit':...",Imbalanced,Support Vector Machine
1,Convabuse,RBF,L2,0.873609,0.841417,"{'explicit': 0.10119236883942766, 'system': 0....",Imbalanced,Support Vector Machine
2,Convabuse,linear,L1,0.094197,0.042533,NaN,Imbalanced,Support Vector Machine
3,Dynamically Generated Hate Speech,Linear,L1,0.827553,0.824574,"{'type': 0.3356863702979971, 'annotator': 0.0,...",Imbalanced,Support Vector Machine
4,Dynamically Generated Hate Speech,RBF,L2,0.645701,0.618876,"{'target_groups': 0.08031265266243284, 'type':...",Imbalanced,Support Vector Machine

In [12]:
svm_classification_resampled.head()

,Dataset,Kernel,Regularization,Accuracy,F1 Score,Permutation Importances,Balance,Model
0,Convabuse,Linear,L1,0.535679,0.513819,"{'system': 0.11788908765652953, 'implicit': 0....",SMOTE,Support Vector Machine
1,Convabuse,RBF,L2,0.535878,0.519120,"{'system': 0.22393162393162394, 'explicit': 0....",SMOTE,Support Vector Machine
2,Convabuse,linear,L1,0.425959,0.367661,"{'system': 0.1969787318624528, 'implicit': 0.0...",SMOTE,Support Vector Machine
3,Dynamically Generated Hate Speech,Linear,L1,0.836848,0.832386,"{'type': 0.33510806536636795, 'annotator': 0.0...",SMOTE,Support Vector Machine
4,Dynamically Generated Hate Speech,RBF,L2,0.738535,0.736685,"{'type': 0.18302583025830263, 'target_groups':...",SMOTE,Support Vector Machine

In [13]:
svm_classification_SMOTE.head()

,Dataset,Kernel,Regularization,Accuracy,F1 Score,Permutation Importances,Balance,Model
0,Convabuse,Linear,L1,0.546954,0.516532,"{'explicit': 0.11790718473616224, 'implicit': ...",SMOTE,Support Vector Machine
1,Convabuse,RBF,L2,0.518533,0.454423,"{'explicit': 0.1814270098380205, 'implicit': 0...",SMOTE,Support Vector Machine
2,Convabuse,linear,L1,0.427010,0.291854,"{'explicit': 0.09825101858292758, 'system': 0....",SMOTE,Support Vector Machine
3,Dynamically Generated Hate Speech,Linear,L1,0.838416,0.834084,"{'type': 0.33962221210741916, 'annotator': 0.0...",SMOTE,Support Vector Machine
4,Dynamically Generated Hate Speech,RBF,L2,0.820323,0.814329,"{'type': 0.24119253527537549, 'target_groups':...",SMOTE,Support Vector Machine

In [14]:
svm_classification_weighted.head()

,Dataset,Kernel,Regularization,Accuracy,F1 Score,Permutation Importances,Balance,Model
0,Convabuse,Linear,L1,0.885533,0.853066,"{'system': 0.08636724960254369, 'explicit': 0....",Weighted,Support Vector Machine
1,Convabuse,RBF,L2,0.869237,0.841503,"{'system': 0.1523052464228935, 'target_groups'...",Weighted,Support Vector Machine
2,Convabuse,linear,L1,0.094197,0.042533,NaN,Weighted,Support Vector Machine
3,Dynamically Generated Hate Speech,Linear,L1,0.827553,0.824574,"{'type': 0.3356863702979971, 'annotator': 0.0,...",Weighted,Support Vector Machine
4,Dynamically Generated Hate Speech,RBF,L2,0.827553,0.824574,"{'type': 0.17979970688812896, 'target_groups':...",Weighted,Support Vector Machine

In [15]:
# Rename F1 Score to F1-score
svm_classification_imbalanced = svm_classification_imbalanced.rename(columns={'F1 Score': 'F1-score'})
svm_classification_resampled = svm_classification_resampled.rename(columns={'F1 Score': 'F1-score'})
svm_classification_SMOTE = svm_classification_SMOTE.rename(columns={'F1 Score': 'F1-score'})
svm_classification_weighted = svm_classification_weighted.rename(columns={'F1 Score': 'F1-score'})

In [16]:
svm_regression_resampled.head()

,Dataset,Kernel,Regularization,RMSE,R2,Permutation Importances,Balance,Model
0,Online Abusive Attacks,Linear,L1,0.206173,0.999989,{'High profanity parents': 0.30193062202308624...,Resampled,Support Vector Machine
1,Online Abusive Attacks,linear,L1,4.030116,0.995804,{'High profanity parents': 0.29917756885580116...,Resampled,Support Vector Machine

In [17]:
# Rename Permutation Importances to Feature Coefficients
svm_regression_resampled = svm_regression_resampled.rename(columns={'Permutation Importances': 'Feature Coefficients'})

In [18]:
dt_classification_imbalanced = pd.read_csv(f"{results_path}model6_dt-classification-summary_imbalanced.csv")
dt_classification_resampled = pd.read_csv(f"{results_path}model6_dt-classification-summary_resampled.csv")
dt_classification_SMOTE = pd.read_csv(f"{results_path}model6_dt-classification-summary_SMOTE.csv")
dt_classification_weighted = pd.read_csv(f"{results_path}model6_dt-classification-summary_weighted.csv")

In [19]:
dt_classification_imbalanced.head()

,Model,Dataset,Kernel,Regularization,Accuracy,F1-score,Ratio,Best Parameters,Importances,Feature Importances,Balance
0,Decision Tree,Convabuse,NaN,NaN,0.876391,0.842223,0.0,"{'dt_classifier__min_samples_split': 404, 'dt_...",{'annotator_id': np.float64(0.0472840733753433...,"{'system': np.float64(0.9377071679802486), 'an...",Imbalanced
1,Decision Tree,Dynamically Generated Hate Speech,NaN,NaN,0.842330,0.841923,0.0,"{'dt_classifier__min_samples_split': 984, 'dt_...","{'type': np.float64(0.7821986185724134), 'anno...","{'type': np.float64(0.7821986185724134), 'orig...",Imbalanced
2,Decision Tree,Online Abusive Attacks,NaN,NaN,0.974082,0.973596,0.0,"{'dt_classifier__min_samples_split': 38, 'dt_c...",{'Toxic parent tweets': np.float64(0.807025867...,{'Toxic parent tweets': np.float64(0.807025867...,Imbalanced
3,Decision Tree,US Elections 2020 Hate Speech,NaN,NaN,0.883139,0.828334,0.0,"{'dt_classifier__min_samples_split': 72, 'dt_c...","{'Trump': np.float64(0.5835398565902453), 'Bid...","{'Trump': np.float64(0.5835398565902453), 'Bid...",Imbalanced
4,Decision Tree,MLMA Hate Speech,NaN,NaN,0.599678,0.493751,0.0,"{'dt_classifier__min_samples_split': 450, 'dt_...","{'implicit': np.float64(0.07052125399746727), ...",{'annotator_sentiment': np.float64(0.879570103...,Imbalanced

In [20]:
dt_classification_resampled.head()

,Model,Dataset,Kernel,Regularization,Accuracy,F1-score,Ratio,Best Parameters,Importances,Feature Importances,Balance
0,Decision Tree,Convabuse,NaN,NaN,0.614788,0.615371,0.0,"{'dt_classifier__min_samples_split': 404, 'dt_...",{'annotator_id': np.float64(0.1625070283324398...,"{'system': np.float64(0.6423965685936481), 'an...",Resampled
1,Decision Tree,Dynamically Generated Hate Speech,NaN,NaN,0.847522,0.846292,0.0,"{'dt_classifier__min_samples_split': 912, 'dt_...","{'type': np.float64(0.7964048907758908), 'anno...","{'type': np.float64(0.7964048907758908), 'orig...",Resampled
2,Decision Tree,Online Abusive Attacks,NaN,NaN,0.935252,0.935062,0.0,"{'dt_classifier__min_samples_split': 180, 'dt_...","{'index': np.float64(0.0), 'Toxic parent tweet...",{'Toxic parent tweets': np.float64(0.769980772...,Resampled
3,Decision Tree,US Elections 2020 Hate Speech,NaN,NaN,0.688447,0.687829,0.0,"{'dt_classifier__min_samples_split': 129, 'dt_...","{'Trump': np.float64(0.5584431077275446), 'Bid...","{'Trump': np.float64(0.5584431077275446), 'Bid...",Resampled
4,Decision Tree,MLMA Hate Speech,NaN,NaN,0.450646,0.432456,0.0,"{'dt_classifier__min_samples_split': 348, 'dt_...","{'implicit': np.float64(0.41365560630568193), ...",{'annotator_sentiment': np.float64(0.479793305...,Resampled

In [21]:
dt_classification_SMOTE.head()

,Model,Dataset,Kernel,Regularization,Accuracy,F1-score,Ratio,Best Parameters,Importances,Feature Importances,Balance
0,Decision Tree,Convabuse,NaN,NaN,0.534036,0.522117,0.0,"{'dt_classifier__min_samples_split': 1209, 'dt...",{'annotator_id': np.float64(0.1569928455921038...,"{'system': np.float64(0.7747161027949291), 'an...",SMOTE
1,Decision Tree,Dynamically Generated Hate Speech,NaN,NaN,0.845812,0.844547,0.0,"{'dt_classifier__min_samples_split': 1408, 'dt...","{'type': np.float64(0.8420953658019769), 'anno...","{'type': np.float64(0.8420953658019769), 'orig...",SMOTE
2,Decision Tree,Online Abusive Attacks,NaN,NaN,0.955036,0.955082,0.0,"{'dt_classifier__min_samples_split': 180, 'dt_...",{'Toxic parent tweets': np.float64(0.729791632...,{'Toxic parent tweets': np.float64(0.729791632...,SMOTE
3,Decision Tree,US Elections 2020 Hate Speech,NaN,NaN,0.704545,0.703456,0.0,"{'dt_classifier__min_samples_split': 129, 'dt_...","{'Trump': np.float64(0.5968140469522171), 'Bid...","{'Trump': np.float64(0.5968140469522171), 'Bid...",SMOTE
4,Decision Tree,MLMA Hate Speech,NaN,NaN,0.447994,0.427240,0.0,"{'dt_classifier__min_samples_split': 1041, 'dt...","{'implicit': np.float64(0.4097066294573626), '...",{'annotator_sentiment': np.float64(0.476346762...,SMOTE

In [22]:
dt_classification_weighted.head()

,Model,Dataset,Kernel,Regularization,Accuracy,F1-score,Ratio,Best Parameters,Importances,Feature Importances,Balance
0,Decision Tree,Convabuse,NaN,NaN,0.559618,0.636134,0.0,"{'dt_classifier__min_samples_split': 303, 'dt_...",{'annotator_id': np.float64(0.1539554361230522...,"{'system': np.float64(0.7899855759607007), 'an...",Weighted
1,Decision Tree,Dynamically Generated Hate Speech,NaN,NaN,0.842330,0.841923,0.0,"{'dt_classifier__min_samples_split': 984, 'dt_...","{'type': np.float64(0.7931119825269024), 'anno...","{'type': np.float64(0.7931119825269024), 'orig...",Weighted
2,Decision Tree,Online Abusive Attacks,NaN,NaN,0.961123,0.962842,0.0,"{'dt_classifier__min_samples_split': 38, 'dt_c...",{'Toxic parent tweets': np.float64(0.754169764...,{'Toxic parent tweets': np.float64(0.754169764...,Weighted
3,Decision Tree,US Elections 2020 Hate Speech,NaN,NaN,0.664441,0.724400,0.0,"{'dt_classifier__min_samples_split': 72, 'dt_c...","{'Trump': np.float64(0.6178174351975475), 'Bid...","{'Trump': np.float64(0.6178174351975475), 'Bid...",Weighted
4,Decision Tree,MLMA Hate Speech,NaN,NaN,0.450161,0.389569,0.0,"{'dt_classifier__min_samples_split': 750, 'dt_...","{'implicit': np.float64(0.0), 'explicit': np.f...","{'explicit': np.float64(1.0), 'abuse_level': n...",Weighted

In [23]:
dt_regression_resampled.head()

,Model,Dataset,RMSE,R2,Best Parameters,Coefficients,Feature Coefficients,Balance
0,Decision Tree,Online Abusive Attacks,19.017708,0.906574,"{'dt_regressor__min_samples_split': 38, 'dt_re...",{'Toxic parent tweets': np.float64(0.726131924...,{'Toxic parent tweets': np.float64(0.726131924...,Resampled

In [24]:
rf_classification_imbalanced.head()

,Model,Dataset,Kernel,Regularization,Accuracy,F1-score,Ratio,Best Parameters,Feature Importances,Balance
0,Random Forest,Convabuse,NaN,NaN,0.883545,0.849268,0.0,"{'rf_classifier__n_estimators': 958, 'rf_class...","{'system': 0.5232683880238173, 'explicit': 0.2...",imbalanced
1,Random Forest,Dynamically Generated Hate Speech,NaN,NaN,0.840498,0.840163,0.0,"{'rf_classifier__n_estimators': 958, 'rf_class...","{'type': 0.6583325371817896, 'target_groups': ...",imbalanced
2,Random Forest,Online Abusive Attacks,NaN,NaN,0.969762,0.968153,0.0,"{'rf_classifier__n_estimators': 958, 'rf_class...","{'Toxic parent tweets': 0.8162596519886234, 'T...",imbalanced
3,Random Forest,US Elections 2020 Hate Speech,NaN,NaN,0.876461,0.818758,0.0,"{'rf_classifier__n_estimators': 795, 'rf_class...","{'Biden': 0.5341675069108166, 'Trump': 0.46583...",imbalanced
4,Random Forest,MLMA Hate Speech,NaN,NaN,0.601554,0.511696,0.0,"{'rf_classifier__n_estimators': 685, 'rf_class...","{'annotator_sentiment': 0.8641681954671636, 'a...",imbalanced

In [25]:
rf_classification_resampled.head()

,Model,Dataset,Kernel,Regularization,Accuracy,F1-score,Ratio,Best Parameters,Feature Importances,Balance
0,Random Forest,Convabuse,NaN,NaN,0.619559,0.620160,0.0,"{'rf_classifier__n_estimators': 958, 'rf_class...","{'system': 0.35402813669632455, 'explicit': 0....",Resampled
1,Random Forest,Dynamically Generated Hate Speech,NaN,NaN,0.852399,0.851308,0.0,"{'rf_classifier__n_estimators': 958, 'rf_class...","{'type': 0.660087768515954, 'target_groups': 0...",Resampled
2,Random Forest,Online Abusive Attacks,NaN,NaN,0.957734,0.957913,0.0,"{'rf_classifier__n_estimators': 958, 'rf_class...","{'Toxic parent tweets': 0.7601576998861873, 'T...",Resampled
3,Random Forest,US Elections 2020 Hate Speech,NaN,NaN,0.703598,0.702632,0.0,"{'rf_classifier__n_estimators': 795, 'rf_class...","{'Biden': 0.6109033025331421, 'Trump': 0.38909...",Resampled
4,Random Forest,MLMA Hate Speech,NaN,NaN,0.441421,0.429746,0.0,"{'rf_classifier__n_estimators': 962, 'rf_class...","{'annotator_sentiment': 0.5050565565734517, 'e...",Resampled

In [26]:
rf_classification_SMOTE.head()

,Model,Dataset,Kernel,Regularization,Accuracy,F1-score,Ratio,Best Parameters,Feature Importances,Balance
0,Random Forest,Convabuse,NaN,NaN,0.883545,0.849268,0.0,"{'rf_classifier__n_estimators': 958, 'rf_class...","{'system': 0.5232683880238173, 'explicit': 0.2...",SMOTE
1,Random Forest,Dynamically Generated Hate Speech,NaN,NaN,0.840498,0.840163,0.0,"{'rf_classifier__n_estimators': 958, 'rf_class...","{'type': 0.6583325371817896, 'target_groups': ...",SMOTE
2,Random Forest,Online Abusive Attacks,NaN,NaN,0.969762,0.968153,0.0,"{'rf_classifier__n_estimators': 958, 'rf_class...","{'Toxic parent tweets': 0.8162596519886234, 'T...",SMOTE
3,Random Forest,US Elections 2020 Hate Speech,NaN,NaN,0.876461,0.818758,0.0,"{'rf_classifier__n_estimators': 795, 'rf_class...","{'Biden': 0.5341675069108166, 'Trump': 0.46583...",SMOTE
4,Random Forest,MLMA Hate Speech,NaN,NaN,0.601554,0.511696,0.0,"{'rf_classifier__n_estimators': 685, 'rf_class...","{'annotator_sentiment': 0.8641681954671636, 'a...",SMOTE

In [27]:
rf_classification_weighted.head()

,Model,Dataset,Kernel,Regularization,Accuracy,F1-score,Ratio,Best Parameters,Feature Importances,Balance
0,Random Forest,Convabuse,NaN,NaN,0.669714,0.737168,0.0,"{'rf_classifier__n_estimators': 886, 'rf_class...","{'system': 0.4531185190330989, 'explicit': 0.2...",Weighted
1,Random Forest,Dynamically Generated Hate Speech,NaN,NaN,0.840498,0.840163,0.0,"{'rf_classifier__n_estimators': 958, 'rf_class...","{'type': 0.6684826874903167, 'target_groups': ...",Weighted
2,Random Forest,Online Abusive Attacks,NaN,NaN,0.963283,0.964974,0.0,"{'rf_classifier__n_estimators': 958, 'rf_class...","{'Toxic parent tweets': 0.7978291606355419, 'T...",Weighted
3,Random Forest,US Elections 2020 Hate Speech,NaN,NaN,0.656093,0.714833,0.0,"{'rf_classifier__n_estimators': 795, 'rf_class...","{'Trump': 0.5298561710641404, 'Biden': 0.47014...",Weighted
4,Random Forest,MLMA Hate Speech,NaN,NaN,0.387996,0.411136,0.0,"{'rf_classifier__n_estimators': 860, 'rf_class...","{'annotator_sentiment': 0.5323081555110233, 'i...",Weighted

In [28]:
knn_classification_imbalanced.head()

,Model,Dataset,Kernel,Regularization,Accuracy,F1-score,Ratio,Best Parameters,Importances,Feature Importances,Balance
0,K-Nearest Neighbors,Convabuse,NaN,NaN,0.885533,0.852027,0.0,"{'knn_classifier__metric': 'euclidean', 'knn_c...","{'annotator_id': np.float64(0.0), 'bot': np.fl...","{'explicit': np.float64(0.08020667726550076), ...",Imbalanced
1,K-Nearest Neighbors,Dynamically Generated Hate Speech,NaN,NaN,0.842330,0.841923,0.0,"{'knn_classifier__metric': 'euclidean', 'knn_c...","{'type': np.float64(0.1768075232046898), 'anno...","{'type': np.float64(0.1768075232046898), 'targ...",Imbalanced
2,K-Nearest Neighbors,Online Abusive Attacks,NaN,NaN,0.993521,0.993524,0.0,"{'knn_classifier__metric': 'euclidean', 'knn_c...",{'Toxic parent tweets': np.float64(0.511663066...,{'Toxic parent tweets': np.float64(0.511663066...,NaN
3,K-Nearest Neighbors,US Elections 2020 Hate Speech,NaN,NaN,0.883139,0.828334,0.0,"{'knn_classifier__metric': 'euclidean', 'knn_c...","{'Trump': np.float64(0.0), 'Biden': np.float64...","{'Trump': np.float64(0.0), 'Biden': np.float64...",Imbalanced
4,K-Nearest Neighbors,MLMA Hate Speech,NaN,NaN,0.599411,0.490359,0.0,"{'knn_classifier__metric': 'euclidean', 'knn_c...","{'implicit': np.float64(0.002063236870310803),...",{'annotator_sentiment': np.float64(0.043113612...,Imbalanced

In [29]:
knn_classification_resampled.head()

,Model,Dataset,Kernel,Regularization,Accuracy,F1-score,Ratio,Best Parameters,Importances,Feature Importances,Balance
0,K-Nearest Neighbors,Convabuse,NaN,NaN,0.619758,0.617044,0.0,"{'knn_classifier__metric': 'euclidean', 'knn_c...",{'annotator_id': np.float64(0.1477241105148082...,"{'system': np.float64(0.17205326972768836), 'a...",Resampled
1,K-Nearest Neighbors,Dynamically Generated Hate Speech,NaN,NaN,0.833026,0.830199,0.0,"{'knn_classifier__metric': 'euclidean', 'knn_c...","{'type': np.float64(0.1812203479177649), 'anno...","{'type': np.float64(0.1812203479177649), 'targ...",Resampled
2,K-Nearest Neighbors,US Elections 2020 Hate Speech,NaN,NaN,0.625000,0.607660,0.0,"{'knn_classifier__metric': 'euclidean', 'knn_c...","{'Trump': np.float64(0.04412878787878789), 'Bi...","{'Biden': np.float64(0.09630681818181819), 'Tr...",Resampled
3,K-Nearest Neighbors,MLMA Hate Speech,NaN,NaN,0.529329,0.521837,0.0,"{'knn_classifier__metric': 'euclidean', 'knn_c...",{'shock_annotator_sentiment': np.float64(0.085...,{'sadness_annotator_sentiment': np.float64(0.0...,Resampled

In [30]:
knn_classification_SMOTE.head()
knn_classification_SMOTE["Balance"] = "SMOTE"

In [31]:
knn_regression_resampled.head()

,Model,Dataset,RMSE,R2,Best Parameters,Coefficients,Feature Coefficients,Balance
0,K-Nearest Neighbors,Online Abusive Attacks,12.522529,0.959493,"{'knn_regressor__metric': 'euclidean', 'knn_re...",{'Parent tweets': np.float64(0.004320409611475...,{'High identity_attack parents': np.float64(0....,Resampled

In [32]:
gb_classification_imbalanced.head()
gb_classification_imbalanced["Balance"] = "Imbalanced"

In [33]:
gb_classification_resampled.head()
gb_classification_resampled["Balance"] = "Resampled"

In [34]:
gb_regression_resampled.head()

Empty DataFrame
Columns: [Model, Dataset, RMSE, R2, Best Parameters, Feature Importances, Resampled]
Index: []

In [35]:
# Rename Feature Importances to Feature Coefficients
gb_regression_resampled = gb_regression_resampled.rename(columns={'Feature Importances': 'Feature Coefficients'})

In [36]:
xgb_classification_imbalanced.head()

,Model,Dataset,Kernel,Regularization,Accuracy,F1-score,Ratio,Best Parameters,Feature Importances,Balance
0,Gradient Boosting,Convabuse,NaN,NaN,0.800079,0.711221,0.0,"{'xgb__learning_rate': np.float64(0.01), 'xgb_...","{'bot': np.float32(0.96887404), 'annotator_id'...",Imbalanced
1,Gradient Boosting,Dynamically Generated Hate Speech,NaN,NaN,0.536639,0.374820,0.0,"{'xgb__learning_rate': np.float64(0.01), 'xgb_...","{'annotator': np.float32(1.0), 'original': np....",Imbalanced
2,Gradient Boosting,Online Abusive Attacks,NaN,NaN,0.477322,0.308445,"{'xgb__learning_rate': np.float64(0.01), 'xgb_...","{'Toxic parent tweets': np.float32(1.0), 'Toxi...",Imbalanced,NaN
3,Gradient Boosting,US Elections 2020 Hate Speech,NaN,NaN,0.883139,0.828334,0.0,"{'xgb__learning_rate': np.float64(0.01), 'xgb_...","{'West': np.float32(0.0), 'Biden': np.float32(...",Imbalanced
4,Gradient Boosting,MLMA Hate Speech,NaN,NaN,0.580922,0.426928,0.0,"{'xgb__learning_rate': np.float64(0.01), 'xgb_...","{'annotator_sentiment': np.float32(1.0), 'abus...",Imbalanced

In [37]:
xgb_classification_resampled.head()

,Model,Dataset,Kernel,Regularization,Accuracy,F1-score,Ratio,Best Parameters,Feature Importances,Balance
0,Gradient Boosting,Convabuse,NaN,NaN,0.199960,0.066642,0.0,"{'xgb__learning_rate': np.float64(0.01), 'xgb_...","{'system': np.float32(0.5363537), 'explicit': ...",Resampled
1,Gradient Boosting,Dynamically Generated Hate Speech,NaN,NaN,0.500000,0.333333,0.0,"{'xgb__learning_rate': np.float64(0.01), 'xgb_...","{'annotator': np.float32(1.0), 'original': np....",Resampled
2,Gradient Boosting,Online Abusive Attacks,NaN,NaN,0.236511,0.140523,{'xgb__learning_rate': np.float64(0.0200000000...,"{'Toxic parent tweets': np.float32(0.7705542),...",Resampled,NaN
3,Gradient Boosting,US Elections 2020 Hate Speech,NaN,NaN,0.500000,0.333333,0.0,"{'xgb__learning_rate': np.float64(0.01), 'xgb_...","{'Trump': np.float32(1.0), 'West': np.float32(...",Resampled
4,Gradient Boosting,MLMA Hate Speech,NaN,NaN,0.250000,0.100000,0.0,{'xgb__learning_rate': np.float64(0.0200000000...,"{'implicit': np.float32(0.6965199), 'annotator...",Resampled

In [38]:
xgb_classification_weighted.head()

,Model,Dataset,Kernel,Regularization,Accuracy,F1-score,Ratio,Best Parameters,Feature Importances,Balance
0,Gradient Boosting,Convabuse,NaN,NaN,0.885533,0.852027,0.0,"{'xgb__learning_rate': np.float64(0.01), 'xgb_...","{'system': np.float32(0.6144965), 'explicit': ...",Weighted
1,Gradient Boosting,Dynamically Generated Hate Speech,NaN,NaN,0.535051,0.518128,0.0,"{'xgb__learning_rate': np.float64(0.01), 'xgb_...","{'annotator': np.float32(1.0), 'original': np....",Weighted
2,Gradient Boosting,Online Abusive Attacks,NaN,NaN,0.758099,0.729504,"{'xgb__learning_rate': np.float64(0.01), 'xgb_...","{'Toxic parent tweets': np.float32(1.0), 'Toxi...",Weighted,NaN
3,Gradient Boosting,US Elections 2020 Hate Speech,NaN,NaN,0.601002,0.668059,0.0,"{'xgb__learning_rate': np.float64(0.01), 'xgb_...","{'Trump': np.float32(1.0), 'West': np.float32(...",Weighted
4,Gradient Boosting,MLMA Hate Speech,NaN,NaN,0.182744,0.120676,0.0,{'xgb__learning_rate': np.float64(0.0200000000...,"{'implicit': np.float32(0.6580093), 'annotator...",Weighted

In [39]:
xgb_regression_resampled.head()

,Model,Dataset,RMSE,R2,Best Parameters,Feature Importances,Resampled
0,Gradient Boosting,Online Abusive Attacks,75.204177,-0.460949,"{'xgb__learning_rate': np.float64(0.1), 'xgb__...",{'Parent tweets with replies': np.float32(0.97...,Resampled

In [40]:
# Rename Feature Importances to Feature Coefficients
xgb_regression_resampled = xgb_regression_resampled.rename(columns={'Feature Importances': 'Feature Coefficients'})

In [41]:
kmeans_clustering_imbalanced.head()

,Dataset,Best Model Silhouette Score,Best Model Inertia,Chosen Model Silhouette Score,Chosen Model Inertia,Best Parameters,Permutation Importances
0,Convabuse,0.513327,50.106688,0.661070,3.098136e+01,"{'init': 'k-means++', 'max_iter': 1, 'n_init':...","{0: array([-5.81469642, 0. , 0. ..."
1,Dynamically Generated Hate Speech,0.603673,869.751854,0.657663,1.641114e+02,"{'init': 'k-means++', 'max_iter': 9, 'n_init':...","{0: array([ 3.26512387, 20.92703093, 324.189..."
2,Online Abusive Attacks,0.400000,40.537527,NaN,1.160907e+00,"{'init': 'k-means++', 'max_iter': 1, 'n_init': 1}","{'feature': ['Toxic parent tweets', 'Toxic rep..."
3,US Elections 2020 Hate Speech,0.666667,3.879310,0.666667,1.048646e-28,"{'init': 'k-means++', 'max_iter': 1, 'n_init': 1}","{0: array([0. , 3.49137931, 3.49137931]..."
4,MLMA Hate Speech,0.659905,50.600016,0.651497,9.166949e+00,"{'init': 'k-means++', 'max_iter': 3, 'n_init': 6}","{0: array([ 0.41154234, 1.8692177 , 86.273111..."

In [42]:
kmeans_clustering_resampled.head()

,Dataset,Best Model Silhouette Score,Best Model Inertia,Chosen Model Silhouette Score,Chosen Model Inertia,Best Parameters,Permutation Importances
0,Convabuse,0.589957,1.812015e+02,0.640346,3.373622e+01,"{'init': 'k-means++', 'max_iter': 1, 'n_init': 1}","{0: array([ 0. , 0. , 5.373..."
1,Dynamically Generated Hate Speech,0.569834,8.285915e+02,0.676209,1.233983e+02,"{'init': 'k-means++', 'max_iter': 2, 'n_init':...","{0: array([ -0.96415169, 20.38557147, 275.651..."
2,Online Abusive Attacks,0.142857,1.827307e+01,0.346683,1.366048e+01,"{'init': 'k-means++', 'max_iter': 11, 'n_init'...","{0: array([2.85723404, 4.41984288, 5.17479508]..."
3,US Elections 2020 Hate Speech,0.636364,2.619265e-30,0.636364,9.856139e-29,"{'init': 'k-means++', 'max_iter': 1, 'n_init': 1}","{0: array([0. , 1.44793814, 3.25786082]..."
4,MLMA Hate Speech,0.448927,1.528755e+02,0.397709,1.352768e+02,"{'init': 'k-means++', 'max_iter': 1, 'n_init': 1}","{0: array([ 5.19310806, 7.8689309 , 16.326459..."

In [43]:
kmeans_clustering_SMOTE.head()

,Dataset,Best Model Silhouette Score,Best Model Inertia,Chosen Model Silhouette Score,Chosen Model Inertia,Best Parameters,Permutation Importances
0,Convabuse,0.624671,231.569622,0.680004,371.483143,"{'init': 'k-means++', 'max_iter': 1, 'n_init': 1}","{0: array([ 0. , 0. , 9.219..."
1,Dynamically Generated Hate Speech,0.605949,973.071098,0.672281,191.073745,"{'init': 'k-means++', 'max_iter': 7, 'n_init': 2}","{0: array([ 3.66216847, 20.3734567 , 391.676..."
2,US Elections 2020 Hate Speech,0.608510,2.744993,0.556711,0.729075,"{'init': 'k-means++', 'max_iter': 1, 'n_init': 3}","{0: array([0. , 2.91904276, 3.76361265]..."
3,MLMA Hate Speech,0.197870,1735.592767,0.302355,1208.708738,"{'init': 'k-means++', 'max_iter': 15, 'n_init'...","{0: array([ 2.06499996, 17.19484697, 17.840..."

In [44]:
sentiment_analysis_linear_regression_imbalanced = pd.read_csv(f"{results_path}sentiment_analysis_model1_linear-model-summary_imbalanced.csv")
sentiment_analysis_linear_regression_resampled = pd.read_csv(f"{results_path}sentiment_analysis_model1_linear-model-summary_resampled.csv")
sentiment_analysis_linear_regression_SMOTE = pd.read_csv(f"{results_path}sentiment_analysis_model1_linear-model-summary_SMOTE.csv")

sentiment_analysis_logistic_regression_imbalanced = pd.read_csv(f"{results_path}sentiment_analysis_model4_logistic-regression-summary_imbalanced.csv")
sentiment_analysis_logistic_regression_resampled = pd.read_csv(f"{results_path}sentiment_analysis_model4_logistic-regression-summary_resampled.csv")
sentiment_analysis_logistic_regression_SMOTE = pd.read_csv(f"{results_path}sentiment_analysis_model4_logistic-regression-summary_SMOTE.csv")
sentiment_analysis_logistic_regression_weighted = pd.read_csv(f"{results_path}sentiment_analysis_model4_logistic-regression-summary_weighted.csv")

sentiment_analysis_decision_tree_imbalanced = pd.read_csv(f"{results_path}sentiment_analysis_model6_dt-classification-summary_imbalanced.csv")
sentiment_analysis_decision_tree_resampled = pd.read_csv(f"{results_path}sentiment_analysis_model6_dt-classification-summary_resampled.csv")
sentiment_analysis_decision_tree_SMOTE = pd.read_csv(f"{results_path}sentiment_analysis_model6_dt-classification-summary_SMOTE.csv")
sentiment_analysis_decision_tree_weighted = pd.read_csv(f"{results_path}sentiment_analysis_model6_dt-classification-summary_weighted.csv")

neural_network_convabuse = pd.read_csv(f"{results_path}model12_neural-network-summary_convabuse_SMOTE.csv")
neural_network_mixed_convabuse = pd.read_csv(f"{results_path}model12_neural-network-summary_convabuse_mixed.csv")
neural_network_mixed_SMOTE_convabuse = pd.read_csv(f"{results_path}model12_neural-network-summary_convabuse_SMOTE_mixed.csv")
neural_network_mixed_mlma = pd.read_csv(f"{results_path}model12_neural-network-summary_mlma_mixed.csv")
neural_network_mixed_SMOTE_mlma = pd.read_csv(f"{results_path}model12_neural-network-summary_mlma_SMOTE_mixed.csv")
neural_network_dghs = pd.read_csv(f"{results_path}model12_neural-network-summary_dghs_SMOTE.csv")
neural_network_mlma = pd.read_csv(f"{results_path}model12_neural-network-summary_mlma_SMOTE.csv")
neural_network_us2020hs = pd.read_csv(f"{results_path}model12_neural-network-summary_us-elections_SMOTE.csv")
neural_network_oaa = pd.read_csv(f"{results_path}model12_neural-network-summary_oaa_SMOTE.csv")

sentiment_analysis_neural_network_imbalanced = pd.read_csv(f"{results_path}sentiment_analysis_model12_neural-network-summary_imbalanced.csv")
sentiment_analysis_neural_network_resampled = pd.read_csv(f"{results_path}sentiment_analysis_model12_neural-network-summary_resampled.csv")
sentiment_analysis_neural_network_SMOTE_Convabuse = pd.read_csv(f"{results_path}sentiment_analysis_model12_neural-network-summary_SMOTE-Convabuse.csv")
sentiment_analysis_neural_network_SMOTE_DGHS = pd.read_csv(f"{results_path}sentiment_analysis_model12_neural-network-summary_SMOTE-DGHS.csv")
sentiment_analysis_neural_network_SMOTE_MLMA = pd.read_csv(f"{results_path}sentiment_analysis_model12_neural-network-summary_SMOTE-MLMA.csv")
sentiment_analysis_neural_network_weighted = pd.read_csv(f"{results_path}sentiment_analysis_model12_neural-network-summary_weighted.csv")

In [45]:
sentiment_analysis_linear_regression_imbalanced.head()

,Model,Dataset,RMSE,R2,Coefficients,Feature Coefficients,Balance
0,Linear Regression,Convabuse combined,0.754713,0.435288,"{0: np.float32(1.0651855), 1: np.float32(-0.87...","{157: np.float32(3.9420588), 197: np.float32(2...",Imbalanced
1,Linear Regression,Convabuse prev_agent,0.979320,0.049150,"{0: np.float32(3.074767), 1: np.float32(1.7563...","{379: np.float32(9.122475), 133: np.float32(7....",Imbalanced
2,Linear Regression,Convabuse prev_user,0.933107,0.136772,"{0: np.float32(-0.0057446556), 1: np.float32(-...","{255: np.float32(2.0723534), 130: np.float32(1...",Imbalanced
3,Linear Regression,Convabuse agent,0.956625,0.092710,"{0: np.float32(-0.69703513), 1: np.float32(2.0...","{338: np.float32(5.636025), 271: np.float32(5....",Imbalanced
4,Linear Regression,Convabuse user,0.639933,0.593995,"{0: np.float32(-0.42043114), 1: np.float32(-0....","{157: np.float32(2.985053), 137: np.float32(1....",Imbalanced

In [46]:
sentiment_analysis_linear_regression_resampled.head()

,Model,Dataset,RMSE,R2,Coefficients,Feature Coefficients,Balance
0,Linear Regression,Convabuse combined,0.922944,0.574045,"{0: np.float32(0.1374525), 1: np.float32(-1.03...","{117: np.float32(4.6621184), 165: np.float32(4...",Resampled
1,Linear Regression,Convabuse prev_agent,1.241402,0.229384,"{0: np.float32(8.48053), 1: np.float32(6.26504...","{355: np.float32(12.886696), 175: np.float32(1...",Resampled
2,Linear Regression,Convabuse prev_user,1.171032,0.314274,"{0: np.float32(-1.4956436), 1: np.float32(-1.8...","{219: np.float32(4.1788597), 130: np.float32(4...",Resampled
3,Linear Regression,Convabuse agent,1.238993,0.232372,"{0: np.float32(-4.9182234), 1: np.float32(3.42...","{110: np.float32(16.329021), 338: np.float32(1...",Resampled
4,Linear Regression,Convabuse user,0.796734,0.682576,"{0: np.float32(0.4993603), 1: np.float32(0.538...","{157: np.float32(4.835052), 117: np.float32(3....",Resampled

In [47]:
sentiment_analysis_linear_regression_SMOTE.head()

,Model,Dataset,RMSE,R2,Coefficients,Feature Coefficients,Balance
0,Linear Regression,Convabuse combined,1.095880,-0.190663,"{0: np.float32(0.78184676), 1: np.float32(-1.7...","{165: np.float32(5.5850844), 382: np.float32(5...",SMOTE
1,Linear Regression,Convabuse prev_agent,1.600719,-1.540347,"{0: np.float32(5.253629), 1: np.float32(5.8551...","{379: np.float32(12.949793), 273: np.float32(9...",SMOTE
2,Linear Regression,Convabuse prev_user,1.555981,-1.400332,"{0: np.float32(-0.6975128), 1: np.float32(-1.5...","{130: np.float32(5.2098746), 169: np.float32(3...",SMOTE
3,Linear Regression,Convabuse agent,1.605151,-1.554435,"{0: np.float32(-0.72618026), 1: np.float32(0.7...","{185: np.float32(9.14351), 3: np.float32(8.625...",SMOTE
4,Linear Regression,Convabuse user,0.906083,0.186048,"{0: np.float32(-1.0281126), 1: np.float32(0.47...","{157: np.float32(5.50272), 117: np.float32(3.2...",SMOTE

In [48]:
sentiment_analysis_logistic_regression_imbalanced.head()

,Dataset,Best Parameters,Accuracy,F1-score,Ratio,Importances,Feature Importances,Balance,Model
0,Convabuse prev_agent,Dataset Convabuse prev_agent\nRegulariz...,0.800079,0.711221,0.0,"{0: np.float64(0.0), 1: np.float64(0.0), 2: np...","{np.int64(141): np.float64(2.201811958740878),...",Imbalanced,Logistic Regression
1,Convabuse prev_user,Dataset Convabuse prev_user\nRegularize...,0.802862,0.720758,0.0,"{0: np.float64(-5.551115123125783e-16), 1: np....",{np.int64(63): np.float64(4.884981308350689e-1...,Imbalanced,Logistic Regression
2,Convabuse agent,Dataset Convabuse agent\nRegularizer ...,0.800874,0.715039,0.0,"{0: np.float64(6.2450045135165055e-15), 1: np....",{np.int64(232): np.float64(8.881784197001252e-...,Imbalanced,Logistic Regression
3,Convabuse user,Dataset Convabuse user\nRegularizer ...,0.852941,0.815526,0.0,"{0: np.float64(7.799316747991725e-15), 1: np.f...",{np.int64(49): np.float64(9.547918011776346e-1...,Imbalanced,Logistic Regression
4,Dynamically Generated Hate Speech target,Dataset Dynamically Generated Hate Spee...,0.766610,0.724676,0.0,"{0: np.float64(-0.3685237008927771), 1: np.flo...","{np.int64(70): np.float64(1.847411601052652), ...",Imbalanced,Logistic Regression

In [49]:
sentiment_analysis_logistic_regression_resampled.head()

,Dataset,Best Parameters,Accuracy,F1-score,Ratio,Importances,Feature Importances,Balance,Model
0,Convabuse combined,Dataset Convabuse combined\nRegularizer...,0.644405,0.641393,0.0,"{0: np.float32(-0.20279072), 1: np.float32(-0....","{np.int64(117): np.float32(8.011974), np.int64...",Resample,Logistic Regression
1,Convabuse combined,Dataset Convabuse combined\nRegularizer...,0.644405,0.641393,0.0,"{0: np.float32(-0.20279072), 1: np.float32(-0....","{np.int64(117): np.float32(8.011974), np.int64...",Resample,Logistic Regression
2,Convabuse prev_agent,Dataset Convabuse prev_agent\nRegulariz...,0.385013,0.390574,0.0,"{0: np.float32(-4.7683716e-07), 1: np.float32(...","{np.int64(17): np.float32(3.349781e-05), np.in...",Resample,Logistic Regression
3,Convabuse prev_user,Dataset Convabuse prev_user\nRegularize...,0.507653,0.505599,0.0,"{0: np.float32(0.6713856), 1: np.float32(-0.13...","{np.int64(112): np.float32(1.100732), np.int64...",Resample,Logistic Regression
4,Convabuse agent,Dataset Convabuse agent\nRegularizer ...,0.407474,0.403481,0.0,"{0: np.float32(0.0), 1: np.float32(-2.5301833)...","{np.int64(260): np.float32(5.9783435), np.int6...",Resample,Logistic Regression

In [50]:
sentiment_analysis_logistic_regression_SMOTE.head()

,Dataset,Best Parameters,Accuracy,F1-score,Ratio,Importances,Feature Importances,Balance,Model
0,Convabuse prev_agent,Dataset Convabuse prev_agent\nRegulariz...,0.404610,0.501601,0.0,"{0: np.float32(-0.8718583), 1: np.float32(6.90...","{np.int64(131): np.float32(11.366352), np.int6...",SMOTE,Logistic Regression
1,Convabuse prev_user,Dataset Convabuse prev_user\nRegularize...,0.471383,0.557337,0.0,"{0: np.float64(-2.6109102025411186), 1: np.flo...","{np.int64(241): np.float64(2.532430360362501),...",SMOTE,Logistic Regression
2,Convabuse agent,Dataset Convabuse agent\nRegularizer ...,0.434022,0.534386,0.0,"{0: np.float32(-8.6307526e-05), 1: np.float32(...","{np.int64(120): np.float32(0.0004708171), np.i...",SMOTE,Logistic Regression
3,Convabuse user,Dataset Convabuse user\nRegularizer ...,0.702305,0.749320,0.0,"{0: np.float64(-1.3322676295501878e-15), 1: np...",{np.int64(123): np.float64(5.972999872483342e-...,SMOTE,Logistic Regression
4,Dynamically Generated Hate Speech target,Dataset Dynamically Generated Hate Spee...,0.681241,0.701729,0.0,"{0: np.float32(-0.40916964), 1: np.float32(-1....","{np.int64(52): np.float32(2.640829), np.int64(...",SMOTE,Logistic Regression

In [51]:
sentiment_analysis_logistic_regression_weighted.head()

,Dataset,Best Parameters,Accuracy,F1-score,Ratio,Importances,Feature Importances,Balance,Model
0,Convabuse prev_agent,Dataset Convabuse prev_agent\nRegulariz...,0.777424,0.716348,0.0,"{0: np.float64(0.0), 1: np.float64(2.499710632...","{np.int64(372): np.float64(6.076499914924293),...",Weighted,Logistic Regression
1,Convabuse prev_user,Dataset Convabuse prev_user\nRegularize...,0.743641,0.731808,0.0,"{0: np.float64(-1.7708077254893646), 1: np.flo...","{np.int64(32): np.float64(3.5929164052075873),...",Weighted,Logistic Regression
2,Convabuse agent,Dataset Convabuse agent\nRegularizer ...,0.772655,0.727399,0.0,"{0: np.float64(0.663785638920268), 1: np.float...",{np.int64(349): np.float64(2.7697395697530993)...,Weighted,Logistic Regression
3,Convabuse user,Dataset Convabuse user\nRegularizer ...,0.821145,0.818922,0.0,"{0: np.float64(-1.5258015791448116), 1: np.flo...",{np.int64(178): np.float64(3.9873663095448513)...,Weighted,Logistic Regression
4,Dynamically Generated Hate Speech target,Dataset Dynamically Generated Hate Spee...,0.674768,0.696595,0.0,"{0: np.float64(0.0), 1: np.float64(-1.23909361...","{np.int64(369): np.float64(2.376824085050205),...",Weighted,Logistic Regression

In [52]:
sentiment_analysis_decision_tree_imbalanced.head()

,Model,Dataset,Kernel,Regularization,Accuracy,F1-score,Ratio,Best Parameters,Importances,Top 10 Importances,Balance
0,Decision Tree,Convabuse combined,NaN,NaN,0.812003,0.745170,0.0,"{'dt_classifier__min_samples_split': 404, 'dt_...","{0: np.float64(0.0), 1: np.float64(0.0), 2: np...","{238: np.float64(0.025151616196727303), 84: np...",Imbalanced
1,Decision Tree,Convabuse prev_agent,NaN,NaN,0.800079,0.711221,0.0,"{'dt_classifier__min_samples_split': 505, 'dt_...","{0: np.float64(0.0), 1: np.float64(0.0), 2: np...","{130: np.float64(0.0), 129: np.float64(0.0), 1...",Imbalanced
2,Decision Tree,Convabuse prev_user,NaN,NaN,0.800079,0.711221,0.0,"{'dt_classifier__min_samples_split': 505, 'dt_...","{0: np.float64(0.0), 1: np.float64(0.0), 2: np...","{129: np.float64(0.0), 128: np.float64(0.0), 1...",Imbalanced
3,Decision Tree,Convabuse agent,NaN,NaN,0.800079,0.711221,0.0,"{'dt_classifier__min_samples_split': 505, 'dt_...","{0: np.float64(0.0), 1: np.float64(0.0), 2: np...","{129: np.float64(0.0), 128: np.float64(0.0), 1...",Imbalanced
4,Decision Tree,Convabuse user,NaN,NaN,0.821542,0.761888,0.0,"{'dt_classifier__min_samples_split': 404, 'dt_...","{0: np.float64(0.0), 1: np.float64(0.0), 2: np...","{238: np.float64(0.025014929950669926), 140: n...",Imbalanced

In [53]:
sentiment_analysis_decision_tree_resampled.head()

,Model,Dataset,Kernel,Regularization,Accuracy,F1-score,Ratio,Best Parameters,Importances,Top 10 Importances,Balance
0,Decision Tree,Convabuse combined,NaN,NaN,0.528324,0.525977,0.0,"{'dt_classifier__min_samples_split': 404, 'dt_...","{0: np.float64(0.0), 1: np.float64(0.0), 2: np...","{186: np.float64(0.02760831633465277), 211: np...",Resample
1,Decision Tree,Convabuse prev_agent,NaN,NaN,0.333135,0.328530,0.0,"{'dt_classifier__min_samples_split': 404, 'dt_...","{0: np.float64(0.0), 1: np.float64(0.0), 2: np...","{113: np.float64(0.030039031058812168), 40: np...",Resample
2,Decision Tree,Convabuse prev_user,NaN,NaN,0.430133,0.424733,0.0,"{'dt_classifier__min_samples_split': 404, 'dt_...","{0: np.float64(0.0), 1: np.float64(0.0), 2: np...","{370: np.float64(0.031056335384902305), 49: np...",Resample
3,Decision Tree,Convabuse agent,NaN,NaN,0.350229,0.352981,0.0,"{'dt_classifier__min_samples_split': 404, 'dt_...","{0: np.float64(0.0), 1: np.float64(0.0), 2: np...","{125: np.float64(0.02992268867269864), 167: np...",Resample
4,Decision Tree,Convabuse user,NaN,NaN,0.560127,0.556992,0.0,"{'dt_classifier__min_samples_split': 404, 'dt_...","{0: np.float64(0.0), 1: np.float64(0.0), 2: np...","{349: np.float64(0.021045551275896513), 354: n...",Resample

In [54]:
sentiment_analysis_decision_tree_SMOTE.head()

,Model,Dataset,Kernel,Regularization,Accuracy,F1-score,Ratio,Best Parameters,Importances,Top 10 Importances,Balance
0,Decision Tree,Convabuse combined,NaN,NaN,0.434817,0.525765,0.0,"{'dt_classifier__min_samples_split': 1209, 'dt...","{0: np.float64(0.0), 1: np.float64(0.0), 2: np...","{119: np.float64(0.02367372865258096), 342: np...",SMOTE
1,Decision Tree,Convabuse prev_agent,NaN,NaN,0.337440,0.426874,0.0,"{'dt_classifier__min_samples_split': 1209, 'dt...","{0: np.float64(0.0), 1: np.float64(0.0), 2: np...","{70: np.float64(0.03197849873940117), 272: np....",SMOTE
2,Decision Tree,Convabuse prev_user,NaN,NaN,0.356518,0.451840,0.0,"{'dt_classifier__min_samples_split': 1209, 'dt...","{0: np.float64(0.0), 1: np.float64(0.0), 2: np...","{349: np.float64(0.028410585615974083), 294: n...",SMOTE
3,Decision Tree,Convabuse agent,NaN,NaN,0.331479,0.436711,0.0,"{'dt_classifier__min_samples_split': 1209, 'dt...","{0: np.float64(0.010725698468945093), 1: np.fl...","{14: np.float64(0.03115684493252797), 148: np....",SMOTE
4,Decision Tree,Convabuse user,NaN,NaN,0.474165,0.569291,0.0,"{'dt_classifier__min_samples_split': 1209, 'dt...","{0: np.float64(0.0), 1: np.float64(0.0), 2: np...","{52: np.float64(0.02651014800499396), 207: np....",SMOTE

In [55]:
sentiment_analysis_decision_tree_weighted.head()

,Model,Dataset,Kernel,Regularization,Accuracy,F1-score,Ratio,Best Parameters,Importances,Top 10 Importances,Balance
0,Decision Tree,Convabuse combined,NaN,NaN,0.394674,0.497042,0.0,"{'dt_classifier__min_samples_split': 505, 'dt_...","{0: np.float64(0.0), 1: np.float64(0.0), 2: np...","{130: np.float64(0.0), 129: np.float64(0.0), 1...",Weighted
1,Decision Tree,Convabuse prev_agent,NaN,NaN,0.314785,0.412079,0.0,"{'dt_classifier__min_samples_split': 303, 'dt_...","{0: np.float64(0.0), 1: np.float64(0.0), 2: np...","{154: np.float64(0.024630483135638814), 289: n...",Weighted
2,Decision Tree,Convabuse prev_user,NaN,NaN,0.286566,0.389073,0.0,"{'dt_classifier__min_samples_split': 505, 'dt_...","{0: np.float64(0.0), 1: np.float64(0.0), 2: np...","{129: np.float64(0.0), 128: np.float64(0.0), 1...",Weighted
3,Decision Tree,Convabuse agent,NaN,NaN,0.276232,0.384161,0.0,"{'dt_classifier__min_samples_split': 404, 'dt_...","{0: np.float64(0.0), 1: np.float64(0.0), 2: np...","{255: np.float64(0.03460473973834215), 123: np...",Weighted
4,Decision Tree,Convabuse user,NaN,NaN,0.511129,0.582295,0.0,"{'dt_classifier__min_samples_split': 404, 'dt_...","{0: np.float64(0.0), 1: np.float64(0.0), 2: np...","{130: np.float64(0.0), 129: np.float64(0.0), 1...",Weighted

In [56]:
# Rename Top 10 Importances to Feature Importances
sentiment_analysis_decision_tree_imbalanced = sentiment_analysis_decision_tree_imbalanced.rename(columns={'Top 10 Importances': 'Feature Importances'})
sentiment_analysis_decision_tree_resampled = sentiment_analysis_decision_tree_resampled.rename(columns={'Top 10 Importances': 'Feature Importances'})
sentiment_analysis_decision_tree_SMOTE = sentiment_analysis_decision_tree_SMOTE.rename(columns={'Top 10 Importances': 'Feature Importances'})
sentiment_analysis_decision_tree_weighted = sentiment_analysis_decision_tree_weighted.rename(columns={'Top 10 Importances': 'Feature Importances'})

In [57]:
sentiment_analysis_neural_network_imbalanced.head()

,Dataset,Model,Optimizer,Accuracy,F1-score,Macro F1-score,Ratio,Best Batch Size,Best Learning Rate,Importances,Feature Importances,Balance
0,Convabuse combined,Neural Network,Adam,0.839428,0.798344,0.334895,0,16,0.0001,"{0: np.float32(3.8368156), 1: np.float32(3.854...","{149: np.float32(5.709761), 245: np.float32(5....",Imbalanced
1,Convabuse prev_agent,Neural Network,Adam,0.800079,0.711221,0.177788,0,8,0.0100,"{0: np.float32(0.04721532), 1: np.float32(0.24...","{288: np.float32(0.41127294), 194: np.float32(...",Imbalanced
2,Convabuse prev_user,Neural Network,Adam,0.813990,0.754209,0.264217,0,64,0.0001,"{0: np.float32(4.7617655), 1: np.float32(3.871...","{347: np.float32(5.2178965), 231: np.float32(5...",Imbalanced
3,Convabuse agent,Neural Network,Adam,0.800079,0.711221,0.177788,0,8,0.0100,"{0: np.float32(0.059801813), 1: np.float32(0.3...","{259: np.float32(0.37208194), 317: np.float32(...",Imbalanced
4,Convabuse user,Neural Network,Adam,0.858506,0.828545,0.440576,0,32,0.0010,"{0: np.float32(2.168736), 1: np.float32(2.4033...","{251: np.float32(3.4352374), 98: np.float32(3....",Imbalanced

In [58]:
sentiment_analysis_neural_network_resampled.head()

,Dataset,Model,Optimizer,Accuracy,F1-score,Macro F1-score,Ratio,Best Batch Size,Best Learning Rate,Importances,Feature Importances,Balance
0,Convabuse combined,Neural Network,Adam,0.809978,0.807973,0.807998,0,8,0.0001,"{0: np.float32(4.244082), 1: np.float32(5.5368...","{381: np.float32(5.448274), 236: np.float32(5....",Resample
1,Convabuse prev_agent,Neural Network,Adam,0.397734,0.403459,0.403467,0,8,0.0001,"{0: np.float32(2.5657277), 1: np.float32(3.864...","{95: np.float32(4.124488), 170: np.float32(4.1...",Resample
2,Convabuse prev_user,Neural Network,Adam,0.651759,0.652532,0.652554,0,8,0.0001,"{0: np.float32(5.0919766), 1: np.float32(4.436...","{359: np.float32(5.391959), 322: np.float32(5....",Resample
3,Convabuse agent,Neural Network,Adam,0.425363,0.420129,0.420145,0,8,0.0001,"{0: np.float32(2.3686876), 1: np.float32(2.809...","{38: np.float32(3.7236476), 330: np.float32(3....",Resample
4,Convabuse user,Neural Network,Adam,0.763069,0.762479,0.762500,0,8,0.0001,"{0: np.float32(4.1903577), 1: np.float32(3.813...","{211: np.float32(4.5467668), 69: np.float32(4....",Resample

In [59]:
sentiment_analysis_neural_network_SMOTE_Convabuse.head()

,Dataset,Model,Optimizer,Accuracy,F1-score,Macro F1-score,Ratio,Best Batch Size,Best Learning Rate,Importances,Feature Importances,Balance
0,Convabuse combined,Neural Network,Adam,0.788553,0.794001,0.399510,0,32,0.001,"{0: np.float32(2.9525266), 1: np.float32(3.345...","{106: np.float32(3.5744166), 60: np.float32(3....",SMOTE
1,Convabuse prev_agent,Neural Network,Adam,0.407790,0.490825,0.171275,0,64,0.010,"{0: np.float32(0.16192095), 1: np.float32(0.44...","{70: np.float32(0.842824), 295: np.float32(0.8...",SMOTE
2,Convabuse prev_user,Neural Network,Adam,0.686010,0.711736,0.308059,0,16,0.001,"{0: np.float32(2.5677962), 1: np.float32(2.419...","{259: np.float32(3.164906), 303: np.float32(3....",SMOTE
3,Convabuse agent,Neural Network,Adam,0.341812,0.419248,0.147137,0,8,0.010,"{0: np.float32(0.06694284), 1: np.float32(0.38...","{162: np.float32(0.54863524), 245: np.float32(...",SMOTE
4,Convabuse user,Neural Network,Adam,0.808824,0.809693,0.418444,0,64,0.001,"{0: np.float32(2.5624537), 1: np.float32(2.761...","{99: np.float32(3.3915524), 211: np.float32(3....",SMOTE

In [60]:
neural_network_convabuse.head()

,Dataset,Model,Optimizer,Accuracy,F1-score,Macro F1-score,Ratio,Best Batch Size,Best Learning Rate,Importances,Feature Importances,Balance
0,Convabuse,Neural Network,Adam,0.606181,0.60689,0.606896,0,128,0.01,"{'annotator_id': np.float32(6.3380985), 'bot':...","{'annotator_id': np.float32(6.3380985), 'bot':...",SMOTE

In [61]:
neural_network_mixed_convabuse.head()

,Dataset,Model,Optimizer,Accuracy,F1-score,Macro F1-score,Ratio,Best Batch Size,Best Learning Rate,Importances,Feature Importances,Balance
0,Convabuse,Neural Network,Adam,0.841812,0.810947,0.352618,0,8,0.01,"{'annotator_id': np.float32(1.2898866), 'bot':...","{'umap_2': np.float32(0.9480864), 'umap_1': np...",Weighted
1,Convabuse,Neural Network,Adam,0.887122,0.852943,0.435361,0,128,0.01,"{'annotator_id': np.float32(4.595064), 'bot': ...","{'annotator_id': np.float32(4.595064), 'bot': ...",Imbalanced

In [62]:
neural_network_mixed_SMOTE_convabuse.head()

,Dataset,Model,Optimizer,Accuracy,F1-score,Macro F1-score,Ratio,Best Batch Size,Best Learning Rate,Importances,Feature Importances,Balance
0,Convabuse,Neural Network,Adam,0.703965,0.703399,0.703407,0,128,0.01,"{'annotator_id': np.float32(7.080337), 'bot': ...","{'annotator_id': np.float32(7.080337), 'bot': ...",SMOTE

In [63]:
neural_network_mixed_mlma.head()

,Dataset,Model,Optimizer,Accuracy,F1-score,Macro F1-score,Ratio,Best Batch Size,Best Learning Rate,Importances,Feature Importances,Balance
0,MLMA Hate Speech,Neural Network,Adam,0.537102,0.504271,0.344168,0,8,0.01,"{'implicit': np.float32(1.3123981), 'explicit'...","{'umap_1': np.float32(1.2173395), 'explicit': ...",Weighted
1,MLMA Hate Speech,Neural Network,Adam,0.608090,0.522185,0.288179,0,128,0.01,"{'implicit': np.float32(1.7540112), 'explicit'...","{'implicit': np.float32(1.7540112), 'explicit'...",Imbalanced

In [64]:
neural_network_mixed_SMOTE_mlma.head()

,Dataset,Model,Optimizer,Accuracy,F1-score,Macro F1-score,Ratio,Best Batch Size,Best Learning Rate,Importances,Feature Importances,Balance
0,MLMA Hate Speech,Neural Network,Adam,0.574031,0.558313,0.558313,0,128,0.01,"{'implicit': np.float32(3.3530564), 'explicit'...","{'implicit': np.float32(3.3530564), 'explicit'...",SMOTE

In [65]:
sentiment_analysis_neural_network_SMOTE_DGHS.head()

,Dataset,Model,Optimizer,Accuracy,F1-score,Macro F1-score,Ratio,Best Batch Size,Best Learning Rate,Importances,Feature Importances,Balance
0,Dynamically Generated Hate Speech target,Neural Network,Adam,0.736688,0.727254,0.618605,0,8,0.0001,"{0: np.float32(3.4428403), 1: np.float32(3.582...","{7: np.float32(3.827003), 112: np.float32(3.83...",SMOTE
1,Dynamically Generated Hate Speech label,Neural Network,Adam,0.724597,0.724628,0.724596,0,64,0.0010,"{0: np.float32(2.6728237), 1: np.float32(2.223...","{359: np.float32(3.5152912), 259: np.float32(3...",SMOTE

In [66]:
neural_network_dghs.head()

,Dataset,Model,Optimizer,Accuracy,F1-score,Macro F1-score,Ratio,Best Batch Size,Best Learning Rate,Importances,Feature Importances,Balance
0,Dynamically Generated Hate Speech,Neural Network,Adam,0.845812,0.844547,0.844547,0,128,0.01,"{'type': np.float32(3.840345), 'annotator': np...","{'type': np.float32(3.840345), 'annotator': np...",SMOTE

In [67]:
sentiment_analysis_neural_network_SMOTE_MLMA.head()

,Dataset,Model,Optimizer,Accuracy,F1-score,Macro F1-score,Ratio,Best Batch Size,Best Learning Rate,Importances,Feature Importances,Balance
0,MLMA Hate Speech target,Neural Network,Adam,0.823373,0.814986,0.710081,0,8,0.001,"{0: np.float32(2.5610127), 1: np.float32(2.534...","{218: np.float32(3.2930164), 347: np.float32(3...",SMOTE

In [68]:
neural_network_mlma.head()

,Dataset,Model,Optimizer,Accuracy,F1-score,Macro F1-score,Ratio,Best Batch Size,Best Learning Rate,Importances,Feature Importances,Balance
0,MLMA Hate Speech,Neural Network,Adam,0.446725,0.426618,0.426618,0,128,0.01,"{'implicit': np.float32(1.8145995), 'explicit'...","{'implicit': np.float32(1.8145995), 'explicit'...",SMOTE

In [69]:
neural_network_us2020hs.head()

,Dataset,Model,Optimizer,Accuracy,F1-score,Macro F1-score,Ratio,Best Batch Size,Best Learning Rate,Importances,Feature Importances,Balance
0,US Elections 2020 Hate Speech,Neural Network,Adam,0.704545,0.703456,0.703456,0,128,0.01,"{'Trump': np.float32(4.310984), 'Biden': np.fl...","{'Trump': np.float32(4.310984), 'Biden': np.fl...",SMOTE

In [70]:
neural_network_oaa.head()

,Dataset,Model,Optimizer,Accuracy,F1-score,Macro F1-score,Ratio,Best Batch Size,Best Learning Rate,Importances,Feature Importances,Balance
0,Online Abusive Attacks,Neural Network,Adam,0.998201,0.998201,0.998198,0,32,0.01,"{'Toxic parent tweets': np.float32(30.791134),...","{'Toxic parent tweets': np.float32(30.791134),...",SMOTE

In [71]:
sentiment_analysis_neural_network_weighted.head()

,Dataset,Model,Optimizer,Accuracy,F1-score,Macro F1-score,Ratio,Best Batch Size,Best Learning Rate,Importances,Feature Importances,Balance
0,Convabuse combined,Neural Network,Adam,0.758744,0.758873,0.342938,0,32,0.010,"{0: np.float32(0.96336144), 1: np.float32(0.58...","{63: np.float32(2.0445862), 310: np.float32(2....",Weighted
1,Convabuse prev_agent,Neural Network,Adam,0.470986,0.542556,0.174649,0,8,0.001,"{0: np.float32(0.7703762), 1: np.float32(1.361...","{303: np.float32(1.8994144), 140: np.float32(1...",Weighted
2,Convabuse prev_user,Neural Network,Adam,0.800079,0.711221,0.177788,0,8,0.010,"{0: np.float32(0.0007538259), 1: np.float32(0....","{382: np.float32(0.00566382), 337: np.float32(...",Weighted
3,Convabuse agent,Neural Network,Adam,0.703895,0.675155,0.185831,0,16,0.010,"{0: np.float32(0.46692193), 1: np.float32(1.39...","{193: np.float32(1.3779825), 115: np.float32(1...",Weighted
4,Convabuse user,Neural Network,Adam,0.773450,0.765733,0.339666,0,8,0.010,"{0: np.float32(0.5396185), 1: np.float32(0.745...","{334: np.float32(1.8374379), 55: np.float32(1....",Weighted

## Results Compilation

In [72]:
# Compile all of the classification results
logistic_regression = pd.concat([logistic_regression_imbalanced, logistic_regression_resampled, logistic_regression_SMOTE, logistic_regression_weighted]).reset_index(drop=True)
svm_classification = pd.concat([svm_classification_imbalanced, svm_classification_resampled, svm_classification_SMOTE, svm_classification_weighted]).reset_index(drop=True)
dt_classification = pd.concat([dt_classification_imbalanced, dt_classification_resampled, dt_classification_SMOTE, dt_classification_weighted]).reset_index(drop=True)
rf_classification = pd.concat([rf_classification_imbalanced, rf_classification_resampled, rf_classification_SMOTE, rf_classification_weighted]).reset_index(drop=True)
knn_classification = pd.concat([knn_classification_imbalanced, knn_classification_resampled, knn_classification_SMOTE]).reset_index(drop=True)
gb_classification = pd.concat([gb_classification_imbalanced, gb_classification_resampled]).reset_index(drop=True)
xgb_classification = pd.concat([xgb_classification_imbalanced, xgb_classification_resampled, xgb_classification_weighted]).reset_index(drop=True)
neural_network_classification = pd.concat([neural_network_convabuse, neural_network_mixed_convabuse, neural_network_mixed_SMOTE_convabuse, neural_network_mixed_mlma, neural_network_mixed_SMOTE_mlma, neural_network_dghs, neural_network_mlma, neural_network_us2020hs, neural_network_oaa]).reset_index(drop=True)
sentiment_analysis_logistic_regression = pd.concat([sentiment_analysis_logistic_regression_imbalanced, sentiment_analysis_logistic_regression_resampled, sentiment_analysis_logistic_regression_SMOTE, sentiment_analysis_logistic_regression_weighted]).reset_index(drop=True)
sentiment_analysis_decision_tree = pd.concat([sentiment_analysis_decision_tree_imbalanced, sentiment_analysis_decision_tree_resampled, sentiment_analysis_decision_tree_SMOTE, sentiment_analysis_decision_tree_weighted]).reset_index(drop=True)
sentiment_analysis_neural_network = pd.concat([sentiment_analysis_neural_network_imbalanced, sentiment_analysis_neural_network_resampled, sentiment_analysis_neural_network_SMOTE_Convabuse, sentiment_analysis_neural_network_SMOTE_DGHS, sentiment_analysis_neural_network_SMOTE_MLMA, sentiment_analysis_neural_network_weighted]).reset_index(drop=True)

In [73]:
# Create a unified classification dataframe
classification_results = pd.concat([logistic_regression, svm_classification, dt_classification, rf_classification, knn_classification, gb_classification, xgb_classification, neural_network_classification, sentiment_analysis_logistic_regression, sentiment_analysis_decision_tree, sentiment_analysis_neural_network]).reset_index(drop=True)

classification_results = classification_results[["Model", "Balance", "Dataset", "Regularizer", "Solver", "Accuracy", "F1-score", "Ratio", "Feature Importances", "Permutation Importances", "Best Parameters"]]

# Replace all NaN values with "None" in Feature Importances, Permutation Importances, and Best Parameters
classification_results = classification_results.fillna("None")

# Replace all Dataset values of "US Elections 2020 Election Hate Speech" to "US Elections 2020 Hate Speech"
classification_results['Dataset'] = classification_results['Dataset'].replace("US Elections 2020 Election Hate Speech", "US Elections 2020 Hate Speech")

# Replace all Dataset values containing "Convabuse" with "Convabuse"
classification_results['Dataset'] = classification_results['Dataset'].replace("Convabuse prev_user", "Convabuse")
classification_results['Dataset'] = classification_results['Dataset'].replace("Convabuse prev_agent", "Convabuse")
classification_results['Dataset'] = classification_results['Dataset'].replace("Convabuse agent", "Convabuse")
classification_results['Dataset'] = classification_results['Dataset'].replace("Convabuse user", "Convabuse")
classification_results['Dataset'] = classification_results['Dataset'].replace("Convabuse combined", "Convabuse")

# Replace all Dataset values containing "Dynamically Generated Hate Speech" or "DGHS" with "Dynamically Generated Hate Speech"
classification_results['Dataset'] = classification_results['Dataset'].replace("Dynamically Generated Hate Speech target", "Dynamically Generated Hate Speech")
classification_results['Dataset'] = classification_results['Dataset'].replace("Dynamically Generated Hate Speech label", "Dynamically Generated Hate Speech")
classification_results['Dataset'] = classification_results['Dataset'].replace("DGHS", "Dynamically Generated Hate Speech")

# Rename all Dataset values containing "MLMA Hate Speech target" to "MLMA Hate Speech"
classification_results['Dataset'] = classification_results['Dataset'].replace("MLMA Hate Speech target", "MLMA Hate Speech")

# Rename all Dataset values containing "US2020HS" to "US Elections 2020 Hate Speech"
classification_results['Dataset'] = classification_results['Dataset'].replace("US2020HS", "US Elections 2020 Hate Speech")

classification_results

,Model,Balance,Dataset,Regularizer,Solver,Accuracy,F1-score,Ratio,Feature Importances,Permutation Importances,Best Parameters
0,Logistic Regression,Imbalanced,Convabuse,l1,liblinear,0.885533,0.852027,0.0,"{'bot': 0.5777202483608284, 'generalised': 0.0...",None,None
1,Logistic Regression,Imbalanced,Dynamically Generated Hate Speech,l1,liblinear,0.827553,0.808568,0.0,"{'original': 3.880785596630201, 'target_groups...",None,None
2,Logistic Regression,Imbalanced,Online Abusive Attacks,l1,saga,0.812095,0.800787,0.0,"{'Toxic replies': -6.170820812897218, 'Toxic p...",None,None
3,Logistic Regression,Imbalanced,US Elections 2020 Hate Speech,l1,liblinear,0.883139,0.000000,0.0,"{'West': 0.0, 'Trump': -0.5047453980305149, 'B...",None,None
4,Logistic Regression,Imbalanced,MLMA Hate Speech,l1,saga,0.596364,0.496579,0.0,"{'Not Abusive': 0.3372934904240555, 'indiffere...",None,None
...,...,...,...,...,...,...,...,...,...,...,...
259,Neural Network,Weighted,Convabuse,None,None,0.703895,0.675155,0,"{193: np.float32(1.3779825), 115: np.float32(1...",None,None
260,Neural Network,Weighted,Convabuse,None,None,0.773450,0.765733,0,"{334: np.float32(1.8374379), 55: np.float32(1....",None,None
261,Neural Network,Weighted,Dynamically Generated Hate Speech,None,None,0.743649,0.754540,0,"{352: np.float32(5.5727615), 245: np.float32(5...",None,None
262,Neural Network,Weighted,Dynamically Generated Hate Speech,None,None,0.727650,0.724477,0,"{201: np.float32(2.97946), 261: np.float32(2.9...",None,None
263,Neural Network,Weighted,MLMA Hate Speech,None,None,0.782205,0.779257,0,"{156: np.float32(6.4274807), 170: np.float32(6...",None,None

In [74]:
classification_results[classification_results["Dataset"] == "US Elections 2020 Hate Speech"].sort_values(by="F1-score", ascending=False)

,Model,Balance,Dataset,Regularizer,Solver,Accuracy,F1-score,Ratio,Feature Importances,Permutation Importances,Best Parameters
29,Support Vector Machine,Imbalanced,US Elections 2020 Hate Speech,None,None,0.883139,0.828334,None,None,"{'Trump': 0.0, 'Biden': 0.0, 'West': 0.0}",None
147,Gradient Boosting,Imbalanced,US Elections 2020 Hate Speech,None,None,0.883139,0.828334,0.0,"{'West': np.float32(0.0), 'Biden': np.float32(...",None,"{'xgb__learning_rate': np.float64(0.01), 'xgb_..."
83,Decision Tree,Imbalanced,US Elections 2020 Hate Speech,None,None,0.883139,0.828334,0.0,"{'Trump': np.float64(0.5835398565902453), 'Bid...",None,"{'dt_classifier__min_samples_split': 72, 'dt_c..."
137,Gradient Boosting,Imbalanced,US Elections 2020 Hate Speech,None,None,0.883139,0.828334,0.0,"{'Biden': np.float64(1.0), 'West': np.float64(...",None,"{'gb__learning_rate': 0.01, 'gb__max_depth': 1..."
123,K-Nearest Neighbors,Imbalanced,US Elections 2020 Hate Speech,None,None,0.883139,0.828334,0.0,"{'Trump': np.float64(0.0), 'Biden': np.float64...",None,"{'knn_classifier__metric': 'euclidean', 'knn_c..."
113,Random Forest,SMOTE,US Elections 2020 Hate Speech,None,None,0.876461,0.818758,0.0,"{'Biden': 0.5341675069108166, 'Trump': 0.46583...",None,"{'rf_classifier__n_estimators': 795, 'rf_class..."
103,Random Forest,imbalanced,US Elections 2020 Hate Speech,None,None,0.876461,0.818758,0.0,"{'Biden': 0.5341675069108166, 'Trump': 0.46583...",None,"{'rf_classifier__n_estimators': 795, 'rf_class..."
31,Support Vector Machine,Imbalanced,US Elections 2020 Hate Speech,None,None,0.776294,0.794436,None,None,"{'Trump': 0.1732888146911519, 'Biden': 0.14574...",None
30,Support Vector Machine,Imbalanced,US Elections 2020 Hate Speech,None,None,0.712855,0.756529,None,None,"{'Trump': 0.045742904841402365, 'Biden': 0.0, ...",None
98,Decision Tree,Weighted,US Elections 2020 Hate Speech,None,None,0.664441,0.724400,0.0,"{'Trump': np.float64(0.6178174351975475), 'Bid...",None,"{'dt_classifier__min_samples_split': 72, 'dt_c..."
118,Random Forest,Weighted,US Elections 2020 Hate Speech,None,None,0.656093,0.714833,0.0,"{'Trump': 0.5298561710641404, 'Biden': 0.47014...",None,"{'rf_classifier__n_estimators': 795, 'rf_class..."
74,Support Vector Machine,Weighted,US Elections 2020 Hate Speech,None,None,0.646077,0.709143,None,None,"{'Biden': 0.12270450751252085, 'Trump': 0.1090...",None
93,Decision Tree,SMOTE,US Elections 2020 Hate Speech,None,None,0.704545,0.703456,0.0,"{'Trump': np.float64(0.5968140469522171), 'Bid...",None,"{'dt_classifier__min_samples_split': 129, 'dt_..."
168,Neural Network,SMOTE,US Elections 2020 Hate Speech,None,None,0.704545,0.703456,0,"{'Trump': np.float32(4.310984), 'Biden': np.fl...",None,None
108,Random Forest,Resampled,US Elections 2020 Hate Speech,None,None,0.703598,0.702632,0.0,"{'Biden': 0.6109033025331421, 'Trump': 0.38909...",None,"{'rf_classifier__n_estimators': 795, 'rf_class..."
132,K-Nearest Neighbors,SMOTE,US Elections 2020 Hate Speech,None,None,0.703598,0.702540,0.0,"{'Trump': np.float64(0.16704545454545455), 'Bi...",None,"{'knn_classifier__metric': 'euclidean', 'knn_c..."
88,Decision Tree,Resampled,US Elections 2020 Hate Speech,None,None,0.688447,0.687829,0.0,"{'Trump': np.float64(0.5584431077275446), 'Bid...",None,"{'dt_classifier__min_samples_split': 129, 'dt_..."
60,Support Vector Machine,SMOTE,US Elections 2020 Hate Speech,None,None,0.673295,0.672976,None,None,"{'Biden': 0.15123106060606065, 'Trump': 0.1204...",None
157,Gradient Boosting,Weighted,US Elections 2020 Hate Speech,None,None,0.601002,0.668059,0.0,"{'Trump': np.float32(1.0), 'West': np.float32(...",None,"{'xgb__learning_rate': np.float64(0.01), 'xgb_..."
46,Support Vector Machine,SMOTE,US Elections 2020 Hate Speech,None,None,0.660985,0.658277,None,None,"{'Trump': 0.13077651515151517, 'Biden': 0.1215...",None
13,Logistic Regression,SMOTE,US Elections 2020 Hate Speech,l1,liblinear,0.648674,0.650330,0.0,"{'West': 0.0, 'Biden': -0.5157701187647922, 'T...",None,None
45,Support Vector Machine,SMOTE,US Elections 2020 Hate Speech,None,None,0.649621,0.649299,None,None,"{'Trump': 0.10890151515151518, 'Biden': 0.0685...",None
142,Gradient Boosting,Resampled,US Elections 2020 Hate Speech,None,None,0.649621,0.649299,0.0,"{'Trump': np.float64(0.8192143402998822), 'Bid...",None,"{'gb__learning_rate': np.float64(0.04), 'gb__m..."
59,Support Vector Machine,SMOTE,US Elections 2020 Hate Speech,None,None,0.648674,0.648666,None,None,"{'Biden': 0.11609848484848484, 'Trump': 0.0739...",None
44,Support Vector Machine,SMOTE,US Elections 2020 Hate Speech,None,None,0.643939,0.643939,None,None,"{'Biden': 0.11268939393939395, 'Trump': 0.0693...",None
8,Logistic Regression,SMOTE,US Elections 2020 Hate Speech,l1,liblinear,0.643939,0.643939,0.0,"{'West': 0.0, 'Trump': -0.5361364908316495, 'B...",None,None
127,K-Nearest Neighbors,Resampled,US Elections 2020 Hate Speech,None,None,0.625000,0.607660,0.0,"{'Biden': np.float64(0.09630681818181819), 'Tr...",None,"{'knn_classifier__metric': 'euclidean', 'knn_c..."
61,Support Vector Machine,SMOTE,US Elections 2020 Hate Speech,None,None,0.548295,0.521702,None,None,"{'Trump': 0.0607954545454546, 'Biden': 0.02490...",None
152,Gradient Boosting,Resampled,US Elections 2020 Hate Speech,None,None,0.500000,0.333333,0.0,"{'Trump': np.float32(1.0), 'West': np.float32(...",None,"{'xgb__learning_rate': np.float64(0.01), 'xgb_..."
18,Logistic Regression,Weighted,US Elections 2020 Hate Speech,l1,liblinear,0.646077,0.307190,0.0,"{'West': 0.0, 'Biden': -0.5153487915313094, 'T...",None,None
75,Support Vector Machine,Weighted,US Elections 2020 Hate Speech,None,None,0.233723,0.269677,None,None,"{'West': 0.0, 'Biden': -0.2547579298831385, 'T...",None
76,Support Vector Machine,Weighted,US Elections 2020 Hate Speech,None,None,0.116861,0.024455,None,None,"{'Trump': 0.0, 'Biden': 0.0, 'West': 0.0}",None
3,Logistic Regression,Imbalanced,US Elections 2020 Hate Speech,l1,liblinear,0.883139,0.000000,0.0,"{'West': 0.0, 'Trump': -0.5047453980305149, 'B...",None,None

In [75]:
# Create a unified classification dataframe
feature_classification_results = pd.concat([logistic_regression, svm_classification, dt_classification, rf_classification, knn_classification, gb_classification, xgb_classification]).reset_index(drop=True)

feature_classification_results = feature_classification_results[["Model", "Balance", "Dataset", "Regularizer", "Solver", "Accuracy", "F1-score", "Ratio", "Feature Importances", "Permutation Importances", "Best Parameters"]]

# Replace all NaN values with "None" in Feature Importances, Permutation Importances, and Best Parameters
feature_classification_results = feature_classification_results.fillna("None")

# Replace all Dataset values of "US Elections 2020 Election Hate Speech" to "US Elections 2020 Hate Speech"
feature_classification_results['Dataset'] = feature_classification_results['Dataset'].replace("US Elections 2020 Election Hate Speech", "US Elections 2020 Hate Speech")

# Replace all Dataset values containing "Convabuse" with "Convabuse"
feature_classification_results['Dataset'] = feature_classification_results['Dataset'].replace("Convabuse prev_user", "Convabuse")
feature_classification_results['Dataset'] = feature_classification_results['Dataset'].replace("Convabuse prev_agent", "Convabuse")
feature_classification_results['Dataset'] = feature_classification_results['Dataset'].replace("Convabuse agent", "Convabuse")
feature_classification_results['Dataset'] = feature_classification_results['Dataset'].replace("Convabuse user", "Convabuse")
feature_classification_results['Dataset'] = feature_classification_results['Dataset'].replace("Convabuse combined", "Convabuse")

# Replace all Dataset values containing "Dynamically Generated Hate Speech" or "DGHS" with "Dynamically Generated Hate Speech"
feature_classification_results['Dataset'] = feature_classification_results['Dataset'].replace("Dynamically Generated Hate Speech target", "Dynamically Generated Hate Speech")
feature_classification_results['Dataset'] = feature_classification_results['Dataset'].replace("Dynamically Generated Hate Speech label", "Dynamically Generated Hate Speech")
feature_classification_results['Dataset'] = feature_classification_results['Dataset'].replace("DGHS", "Dynamically Generated Hate Speech")

# Rename all Dataset values containing "MLMA Hate Speech target" to "MLMA Hate Speech"
feature_classification_results['Dataset'] = feature_classification_results['Dataset'].replace("MLMA Hate Speech target", "MLMA Hate Speech")

# Rename all Dataset values containing "US2020HS" to "US Elections 2020 Hate Speech"
feature_classification_results['Dataset'] = feature_classification_results['Dataset'].replace("US2020HS", "US Elections 2020 Hate Speech")

feature_classification_results

,Model,Balance,Dataset,Regularizer,Solver,Accuracy,F1-score,Ratio,Feature Importances,Permutation Importances,Best Parameters
0,Logistic Regression,Imbalanced,Convabuse,l1,liblinear,0.885533,0.852027,0.0,"{'bot': 0.5777202483608284, 'generalised': 0.0...",None,None
1,Logistic Regression,Imbalanced,Dynamically Generated Hate Speech,l1,liblinear,0.827553,0.808568,0.0,"{'original': 3.880785596630201, 'target_groups...",None,None
2,Logistic Regression,Imbalanced,Online Abusive Attacks,l1,saga,0.812095,0.800787,0.0,"{'Toxic replies': -6.170820812897218, 'Toxic p...",None,None
3,Logistic Regression,Imbalanced,US Elections 2020 Hate Speech,l1,liblinear,0.883139,0.000000,0.0,"{'West': 0.0, 'Trump': -0.5047453980305149, 'B...",None,None
4,Logistic Regression,Imbalanced,MLMA Hate Speech,l1,saga,0.596364,0.496579,0.0,"{'Not Abusive': 0.3372934904240555, 'indiffere...",None,None
...,...,...,...,...,...,...,...,...,...,...,...
154,Gradient Boosting,Weighted,Convabuse,None,None,0.885533,0.852027,0.0,"{'system': np.float32(0.6144965), 'explicit': ...",None,"{'xgb__learning_rate': np.float64(0.01), 'xgb_..."
155,Gradient Boosting,Weighted,Dynamically Generated Hate Speech,None,None,0.535051,0.518128,0.0,"{'annotator': np.float32(1.0), 'original': np....",None,"{'xgb__learning_rate': np.float64(0.01), 'xgb_..."
156,Gradient Boosting,None,Online Abusive Attacks,None,None,0.758099,0.729504,"{'xgb__learning_rate': np.float64(0.01), 'xgb_...",Weighted,None,"{'Toxic parent tweets': np.float32(1.0), 'Toxi..."
157,Gradient Boosting,Weighted,US Elections 2020 Hate Speech,None,None,0.601002,0.668059,0.0,"{'Trump': np.float32(1.0), 'West': np.float32(...",None,"{'xgb__learning_rate': np.float64(0.01), 'xgb_..."
158,Gradient Boosting,Weighted,MLMA Hate Speech,None,None,0.182744,0.120676,0.0,"{'implicit': np.float32(0.6580093), 'annotator...",None,{'xgb__learning_rate': np.float64(0.0200000000...

In [76]:
# Create a unified classification dataframe
embedding_classification_results = pd.concat([sentiment_analysis_logistic_regression, sentiment_analysis_decision_tree, sentiment_analysis_neural_network]).reset_index(drop=True)

embedding_classification_results = embedding_classification_results[["Model", "Balance", "Dataset", "Accuracy", "F1-score", "Ratio", "Feature Importances", "Best Parameters"]]

# Replace all NaN values with "None" in Feature Importances, Permutation Importances, and Best Parameters
embedding_classification_results = embedding_classification_results.fillna("None")

# Replace all Dataset values of "US Elections 2020 Election Hate Speech" to "US Elections 2020 Hate Speech"
embedding_classification_results['Dataset'] = embedding_classification_results['Dataset'].replace("US Elections 2020 Election Hate Speech", "US Elections 2020 Hate Speech")

# Replace all Dataset values containing "Convabuse" with "Convabuse"
embedding_classification_results['Dataset'] = embedding_classification_results['Dataset'].replace("Convabuse prev_user", "Convabuse")
embedding_classification_results['Dataset'] = embedding_classification_results['Dataset'].replace("Convabuse prev_agent", "Convabuse")
embedding_classification_results['Dataset'] = embedding_classification_results['Dataset'].replace("Convabuse agent", "Convabuse")
embedding_classification_results['Dataset'] = embedding_classification_results['Dataset'].replace("Convabuse user", "Convabuse")
embedding_classification_results['Dataset'] = embedding_classification_results['Dataset'].replace("Convabuse combined", "Convabuse")

# Replace all Dataset values containing "Dynamically Generated Hate Speech" or "DGHS" with "Dynamically Generated Hate Speech"
embedding_classification_results['Dataset'] = embedding_classification_results['Dataset'].replace("Dynamically Generated Hate Speech target", "Dynamically Generated Hate Speech")
embedding_classification_results['Dataset'] = embedding_classification_results['Dataset'].replace("Dynamically Generated Hate Speech label", "Dynamically Generated Hate Speech")
embedding_classification_results['Dataset'] = embedding_classification_results['Dataset'].replace("DGHS", "Dynamically Generated Hate Speech")

# Rename all Dataset values containing "MLMA Hate Speech target" to "MLMA Hate Speech"
embedding_classification_results['Dataset'] = embedding_classification_results['Dataset'].replace("MLMA Hate Speech target", "MLMA Hate Speech")

# Rename all Dataset values containing "US2020HS" to "US Elections 2020 Hate Speech"
embedding_classification_results['Dataset'] = embedding_classification_results['Dataset'].replace("US2020HS", "US Elections 2020 Hate Speech")

embedding_classification_results

,Model,Balance,Dataset,Accuracy,F1-score,Ratio,Feature Importances,Best Parameters
0,Logistic Regression,Imbalanced,Convabuse,0.800079,0.711221,0.0,"{np.int64(141): np.float64(2.201811958740878),...",Dataset Convabuse prev_agent\nRegulariz...
1,Logistic Regression,Imbalanced,Convabuse,0.802862,0.720758,0.0,{np.int64(63): np.float64(4.884981308350689e-1...,Dataset Convabuse prev_user\nRegularize...
2,Logistic Regression,Imbalanced,Convabuse,0.800874,0.715039,0.0,{np.int64(232): np.float64(8.881784197001252e-...,Dataset Convabuse agent\nRegularizer ...
3,Logistic Regression,Imbalanced,Convabuse,0.852941,0.815526,0.0,{np.int64(49): np.float64(9.547918011776346e-1...,Dataset Convabuse user\nRegularizer ...
4,Logistic Regression,Imbalanced,Dynamically Generated Hate Speech,0.766610,0.724676,0.0,"{np.int64(70): np.float64(1.847411601052652), ...",Dataset Dynamically Generated Hate Spee...
...,...,...,...,...,...,...,...,...
89,Neural Network,Weighted,Convabuse,0.703895,0.675155,0.0,"{193: np.float32(1.3779825), 115: np.float32(1...",None
90,Neural Network,Weighted,Convabuse,0.773450,0.765733,0.0,"{334: np.float32(1.8374379), 55: np.float32(1....",None
91,Neural Network,Weighted,Dynamically Generated Hate Speech,0.743649,0.754540,0.0,"{352: np.float32(5.5727615), 245: np.float32(5...",None
92,Neural Network,Weighted,Dynamically Generated Hate Speech,0.727650,0.724477,0.0,"{201: np.float32(2.97946), 261: np.float32(2.9...",None
93,Neural Network,Weighted,MLMA Hate Speech,0.782205,0.779257,0.0,"{156: np.float32(6.4274807), 170: np.float32(6...",None

In [77]:
# Compile all of the regression results
linear_regression = pd.concat([linear_regression_imbalanced, linear_regression_resampled, linear_regression_SMOTE]).reset_index(drop=True)
sentiment_analysis_linear_regression = pd.concat([sentiment_analysis_linear_regression_imbalanced, sentiment_analysis_linear_regression_resampled, sentiment_analysis_linear_regression_SMOTE]).reset_index(drop=True)
regression_results = pd.concat([linear_regression, svm_regression_resampled, dt_regression_resampled, gb_regression_resampled, xgb_regression_resampled, knn_regression_resampled, sentiment_analysis_linear_regression]).reset_index(drop=True)
regression_results = regression_results[["Model", "Dataset", "Balance", "RMSE", "R2", "Feature Coefficients", "Best Parameters"]]

# Replace all Dataset values containing "Convabuse" with "Convabuse"
regression_results['Dataset'] = regression_results['Dataset'].replace("Convabuse prev_user", "Convabuse")
regression_results['Dataset'] = regression_results['Dataset'].replace("Convabuse prev_agent", "Convabuse")
regression_results['Dataset'] = regression_results['Dataset'].replace("Convabuse agent", "Convabuse")
regression_results['Dataset'] = regression_results['Dataset'].replace("Convabuse user", "Convabuse")
regression_results['Dataset'] = regression_results['Dataset'].replace("Convabuse combined", "Convabuse")

# Replace all Dataset values containing "Dynamically Generated Hate Speech" or "DGHS" with "Dynamically Generated Hate Speech"
regression_results['Dataset'] = regression_results['Dataset'].replace("Dynamically Generated Hate Speech target", "Dynamically Generated Hate Speech")
regression_results['Dataset'] = regression_results['Dataset'].replace("Dynamically Generated Hate Speech label", "Dynamically Generated Hate Speech")
regression_results['Dataset'] = regression_results['Dataset'].replace("DGHS", "Dynamically Generated Hate Speech")

# Rename all Dataset values containing "MLMA Hate Speech target" to "MLMA Hate Speech"
regression_results['Dataset'] = regression_results['Dataset'].replace("MLMA Hate Speech target", "MLMA Hate Speech")

# Fill NaN values with "None"
regression_results = regression_results.fillna("None")
regression_results

/tmp/ipython-input-3828923713.py:4: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  regression_results = pd.concat([linear_regression, svm_regression_resampled, dt_regression_resampled, gb_regression_resampled, xgb_regression_resampled, knn_regression_resampled, sentiment_analysis_linear_regression]).reset_index(drop=True)

,Model,Dataset,Balance,RMSE,R2,Feature Coefficients,Best Parameters
0,Linear Regression,Convabuse,Imbalanced,3.301153e-01,0.891958,"{'system': np.float64(0.48385017824834126), 'e...",None
1,Linear Regression,Dynamically Generated Hate Speech,Imbalanced,3.381331e-01,0.540195,"{'original': np.float64(0.10876639976590403), ...",None
2,Linear Regression,US Elections 2020 Hate Speech,Imbalanced,3.107905e-01,0.064087,"{'West': np.float64(0.0), 'Trump': np.float64(...",None
3,Linear Regression,MLMA Hate Speech,Imbalanced,6.713010e-01,0.076915,{'sadness_annotator_sentiment': np.float64(0.0...,None
4,Linear Regression,Convabuse,Resampled,6.394386e-01,0.795539,"{'system': np.float64(0.6812356291906492), 'ex...",None
5,Linear Regression,Dynamically Generated Hate Speech,Resampled,3.349200e-01,0.551314,"{'original': np.float64(0.10320610623148284), ...",None
6,Linear Regression,Online Abusive Attacks,Resampled,3.541690e-13,1.000000,{'High profanity parents': np.float64(22.62607...,None
7,Linear Regression,US Elections 2020 Hate Speech,Resampled,4.710882e-01,0.112304,"{'West': np.float64(0.0), 'Trump': np.float64(...",None
8,Linear Regression,MLMA Hate Speech,Resampled,1.023212e+00,0.162586,{'sadness_annotator_sentiment': np.float64(0.1...,None
9,Linear Regression,Convabuse,SMOTE,6.452834e-01,0.791794,"{'explicit': np.float64(0.45529909401421254), ...",None
10,Linear Regression,Dynamically Generated Hate Speech,SMOTE,3.330853e-01,0.556217,"{'original': np.float64(0.10397921440364759), ...",None
11,Linear Regression,US Elections 2020 Hate Speech,SMOTE,4.667787e-01,0.128471,"{'West': np.float64(0.0), 'Trump': np.float64(...",None
12,Linear Regression,MLMA Hate Speech,SMOTE,1.026703e+00,0.156705,{'sadness_annotator_sentiment': np.float64(0.1...,None
13,Support Vector Machine,Online Abusive Attacks,Resampled,2.061727e-01,0.999989,{'High profanity parents': 0.30193062202308624...,None
14,Support Vector Machine,Online Abusive Attacks,Resampled,4.030116e+00,0.995804,{'High profanity parents': 0.29917756885580116...,None
15,Decision Tree,Online Abusive Attacks,Resampled,1.901771e+01,0.906574,{'Toxic parent tweets': np.float64(0.726131924...,"{'dt_regressor__min_samples_split': 38, 'dt_re..."
16,Gradient Boosting,Online Abusive Attacks,None,7.520418e+01,-0.460949,{'Parent tweets with replies': np.float32(0.97...,"{'xgb__learning_rate': np.float64(0.1), 'xgb__..."
17,K-Nearest Neighbors,Online Abusive Attacks,Resampled,1.252253e+01,0.959493,{'High identity_attack parents': np.float64(0....,"{'knn_regressor__metric': 'euclidean', 'knn_re..."
18,Linear Regression,Convabuse,Imbalanced,7.547133e-01,0.435288,"{157: np.float32(3.9420588), 197: np.float32(2...",None
19,Linear Regression,Convabuse,Imbalanced,9.793201e-01,0.049150,"{379: np.float32(9.122475), 133: np.float32(7....",None
20,Linear Regression,Convabuse,Imbalanced,9.331070e-01,0.136772,"{255: np.float32(2.0723534), 130: np.float32(1...",None
21,Linear Regression,Convabuse,Imbalanced,9.566249e-01,0.092710,"{338: np.float32(5.636025), 271: np.float32(5....",None
22,Linear Regression,Convabuse,Imbalanced,6.399325e-01,0.593995,"{157: np.float32(2.985053), 137: np.float32(1....",None
23,Linear Regression,Dynamically Generated Hate Speech,Imbalanced,4.002255e-01,0.131682,"{157: np.float32(0.6667561), 224: np.float32(0...",None
24,Linear Regression,Dynamically Generated Hate Speech,Imbalanced,4.377993e-01,0.229188,"{206: np.float32(0.9047715), 157: np.float32(0...",None
25,Linear Regression,MLMA Hate Speech,Imbalanced,5.689815e-01,0.087107,"{283: np.float32(1.1190851), 181: np.float32(1...",None
26,Linear Regression,Convabuse,Resampled,9.229437e-01,0.574045,"{117: np.float32(4.6621184), 165: np.float32(4...",None
27,Linear Regression,Convabuse,Resampled,1.241402e+00,0.229384,"{355: np.float32(12.886696), 175: np.float32(1...",None
28,Linear Regression,Convabuse,Resampled,1.171032e+00,0.314274,"{219: np.float32(4.1788597), 130: np.float32(4...",None
29,Linear Regression,Convabuse,Resampled,1.238993e+00,0.232372,"{110: np.float32(16.329021), 338: np.float32(1...",None
30,Linear Regression,Convabuse,Resampled,7.967343e-01,0.682576,"{157: np.float32(4.835052), 117: np.float32(3....",None
31,Linear Regression,Dynamically Generated Hate Speech,Resampled,3.898344e-01,0.136233,"{157: np.float32(0.59070706), 312: np.float32(...",None
32,Linear Regression,Dynamically Generated Hate Speech,Resampled,4.403156e-01,0.224489,"{206: np.float32(0.92953193), 99: np.float32(0...",None
33,Linear Regression,MLMA Hate Speech,Resampled,5.689815e-01,0.087107,"{283: np.float32(1.1190851), 181: np.float32(1...",None
34,Linear Regression,Convabuse,SMOTE,1.095880e+00,-0.190663,"{165: np.float32(5.5850844), 382: np.float32(5...",None
35,Linear Regression,Convabuse,SMOTE,1.600719e+00,-1.540347,"{379: np.float32(12.949793), 273: np.float32(9...",None
36,Linear Regression,Convabuse,SMOTE,1.555981e+00,-1.400332,"{130: np.float32(5.2098746), 169: np.float32(3...",None
37,Linear Regression,Convabuse,SMOTE,1.605151e+00,-1.554435,"{185: np.float32(9.14351), 3: np.float32(8.625...",None
38,Linear Regression,Convabuse,SMOTE,9.060830e-01,0.186048,"{157: np.float32(5.50272), 117: np.float32(3.2...",None
39,Linear Regression,Dynamically Generated Hate Speech,SMOTE,4.546767e-01,-0.120663,"{268: np.float32(0.8433245), 224: np.float32(0...",None
40,Linear Regression,Dynamically Generated Hate Speech,SMOTE,4.393081e-01,0.223866,"{206: np.float32(0.9347662), 99: np.float32(0....",None
41,Linear Regression,MLMA Hate Speech,SMOTE,8.073390e-01,-0.837957,"{283: np.float32(3.896449), 186: np.float32(3....",None

In [78]:
kmeans_clustering = pd.concat([kmeans_clustering_imbalanced, kmeans_clustering_resampled, kmeans_clustering_SMOTE]).reset_index(drop=True)
kmeans_clustering

,Dataset,Best Model Silhouette Score,Best Model Inertia,Chosen Model Silhouette Score,Chosen Model Inertia,Best Parameters,Permutation Importances
0,Convabuse,0.513327,5.010669e+01,0.661070,3.098136e+01,"{'init': 'k-means++', 'max_iter': 1, 'n_init':...","{0: array([-5.81469642, 0. , 0. ..."
1,Dynamically Generated Hate Speech,0.603673,8.697519e+02,0.657663,1.641114e+02,"{'init': 'k-means++', 'max_iter': 9, 'n_init':...","{0: array([ 3.26512387, 20.92703093, 324.189..."
2,Online Abusive Attacks,0.400000,4.053753e+01,NaN,1.160907e+00,"{'init': 'k-means++', 'max_iter': 1, 'n_init': 1}","{'feature': ['Toxic parent tweets', 'Toxic rep..."
3,US Elections 2020 Hate Speech,0.666667,3.879310e+00,0.666667,1.048646e-28,"{'init': 'k-means++', 'max_iter': 1, 'n_init': 1}","{0: array([0. , 3.49137931, 3.49137931]..."
4,MLMA Hate Speech,0.659905,5.060002e+01,0.651497,9.166949e+00,"{'init': 'k-means++', 'max_iter': 3, 'n_init': 6}","{0: array([ 0.41154234, 1.8692177 , 86.273111..."
5,Convabuse,0.589957,1.812015e+02,0.640346,3.373622e+01,"{'init': 'k-means++', 'max_iter': 1, 'n_init': 1}","{0: array([ 0. , 0. , 5.373..."
6,Dynamically Generated Hate Speech,0.569834,8.285915e+02,0.676209,1.233983e+02,"{'init': 'k-means++', 'max_iter': 2, 'n_init':...","{0: array([ -0.96415169, 20.38557147, 275.651..."
7,Online Abusive Attacks,0.142857,1.827307e+01,0.346683,1.366048e+01,"{'init': 'k-means++', 'max_iter': 11, 'n_init'...","{0: array([2.85723404, 4.41984288, 5.17479508]..."
8,US Elections 2020 Hate Speech,0.636364,2.619265e-30,0.636364,9.856139e-29,"{'init': 'k-means++', 'max_iter': 1, 'n_init': 1}","{0: array([0. , 1.44793814, 3.25786082]..."
9,MLMA Hate Speech,0.448927,1.528755e+02,0.397709,1.352768e+02,"{'init': 'k-means++', 'max_iter': 1, 'n_init': 1}","{0: array([ 5.19310806, 7.8689309 , 16.326459..."
10,Convabuse,0.624671,2.315696e+02,0.680004,3.714831e+02,"{'init': 'k-means++', 'max_iter': 1, 'n_init': 1}","{0: array([ 0. , 0. , 9.219..."
11,Dynamically Generated Hate Speech,0.605949,9.730711e+02,0.672281,1.910737e+02,"{'init': 'k-means++', 'max_iter': 7, 'n_init': 2}","{0: array([ 3.66216847, 20.3734567 , 391.676..."
12,US Elections 2020 Hate Speech,0.608510,2.744993e+00,0.556711,7.290754e-01,"{'init': 'k-means++', 'max_iter': 1, 'n_init': 3}","{0: array([0. , 2.91904276, 3.76361265]..."
13,MLMA Hate Speech,0.197870,1.735593e+03,0.302355,1.208709e+03,"{'init': 'k-means++', 'max_iter': 15, 'n_init'...","{0: array([ 2.06499996, 17.19484697, 17.840..."

## Dataset Results

In [79]:
# Get all classification results for Convabuse
classification_results[classification_results["Dataset"] == "Convabuse"][classification_results["F1-score"] > 0.6][classification_results["Model"] == "Neural Network"].sort_values(by="F1-score", ascending=False)

/tmp/ipython-input-301479233.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  classification_results[classification_results["Dataset"] == "Convabuse"][classification_results["F1-score"] > 0.6][classification_results["Model"] == "Neural Network"].sort_values(by="F1-score", ascending=False)
/tmp/ipython-input-301479233.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  classification_results[classification_results["Dataset"] == "Convabuse"][classification_results["F1-score"] > 0.6][classification_results["Model"] == "Neural Network"].sort_values(by="F1-score", ascending=False)

,Model,Balance,Dataset,Regularizer,Solver,Accuracy,F1-score,Ratio,Feature Importances,Permutation Importances,Best Parameters
161,Neural Network,Imbalanced,Convabuse,None,None,0.887122,0.852943,0,"{'annotator_id': np.float32(4.595064), 'bot': ...",None,None
236,Neural Network,Imbalanced,Convabuse,None,None,0.858506,0.828545,0,"{251: np.float32(3.4352374), 98: np.float32(3....",None,None
160,Neural Network,Weighted,Convabuse,None,None,0.841812,0.810947,0,"{'umap_2': np.float32(0.9480864), 'umap_1': np...",None,None
252,Neural Network,SMOTE,Convabuse,None,None,0.808824,0.809693,0,"{99: np.float32(3.3915524), 211: np.float32(3....",None,None
240,Neural Network,Resample,Convabuse,None,None,0.809978,0.807973,0,"{381: np.float32(5.448274), 236: np.float32(5....",None,None
232,Neural Network,Imbalanced,Convabuse,None,None,0.839428,0.798344,0,"{149: np.float32(5.709761), 245: np.float32(5....",None,None
248,Neural Network,SMOTE,Convabuse,None,None,0.788553,0.794001,0,"{106: np.float32(3.5744166), 60: np.float32(3....",None,None
260,Neural Network,Weighted,Convabuse,None,None,0.773450,0.765733,0,"{334: np.float32(1.8374379), 55: np.float32(1....",None,None
244,Neural Network,Resample,Convabuse,None,None,0.763069,0.762479,0,"{211: np.float32(4.5467668), 69: np.float32(4....",None,None
256,Neural Network,Weighted,Convabuse,None,None,0.758744,0.758873,0,"{63: np.float32(2.0445862), 310: np.float32(2....",None,None
234,Neural Network,Imbalanced,Convabuse,None,None,0.813990,0.754209,0,"{347: np.float32(5.2178965), 231: np.float32(5...",None,None
250,Neural Network,SMOTE,Convabuse,None,None,0.686010,0.711736,0,"{259: np.float32(3.164906), 303: np.float32(3....",None,None
258,Neural Network,Weighted,Convabuse,None,None,0.800079,0.711221,0,"{382: np.float32(0.00566382), 337: np.float32(...",None,None
233,Neural Network,Imbalanced,Convabuse,None,None,0.800079,0.711221,0,"{288: np.float32(0.41127294), 194: np.float32(...",None,None
235,Neural Network,Imbalanced,Convabuse,None,None,0.800079,0.711221,0,"{259: np.float32(0.37208194), 317: np.float32(...",None,None
162,Neural Network,SMOTE,Convabuse,None,None,0.703965,0.703399,0,"{'annotator_id': np.float32(7.080337), 'bot': ...",None,None
259,Neural Network,Weighted,Convabuse,None,None,0.703895,0.675155,0,"{193: np.float32(1.3779825), 115: np.float32(1...",None,None
242,Neural Network,Resample,Convabuse,None,None,0.651759,0.652532,0,"{359: np.float32(5.391959), 322: np.float32(5....",None,None
159,Neural Network,SMOTE,Convabuse,None,None,0.606181,0.606890,0,"{'annotator_id': np.float32(6.3380985), 'bot':...",None,None

In [80]:
# Get all classification results for DGHS
classification_results[classification_results["Dataset"] == "Dynamically Generated Hate Speech"][classification_results["Model"] == "Neural Network"][classification_results["F1-score"] > 0.6].sort_values(by="F1-score", ascending=False)

/tmp/ipython-input-1319333015.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  classification_results[classification_results["Dataset"] == "Dynamically Generated Hate Speech"][classification_results["Model"] == "Neural Network"][classification_results["F1-score"] > 0.6].sort_values(by="F1-score", ascending=False)
/tmp/ipython-input-1319333015.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  classification_results[classification_results["Dataset"] == "Dynamically Generated Hate Speech"][classification_results["Model"] == "Neural Network"][classification_results["F1-score"] > 0.6].sort_values(by="F1-score", ascending=False)

,Model,Balance,Dataset,Regularizer,Solver,Accuracy,F1-score,Ratio,Feature Importances,Permutation Importances,Best Parameters
166,Neural Network,SMOTE,Dynamically Generated Hate Speech,None,None,0.845812,0.844547,0,"{'type': np.float32(3.840345), 'annotator': np...",None,None
245,Neural Network,Resample,Dynamically Generated Hate Speech,None,None,0.813785,0.810761,0,"{292: np.float32(4.6578193), 17: np.float32(4....",None,None
237,Neural Network,Imbalanced,Dynamically Generated Hate Speech,None,None,0.781387,0.763437,0,"{7: np.float32(4.476304), 349: np.float32(4.50...",None,None
261,Neural Network,Weighted,Dynamically Generated Hate Speech,None,None,0.743649,0.754540,0,"{352: np.float32(5.5727615), 245: np.float32(5...",None,None
246,Neural Network,Resample,Dynamically Generated Hate Speech,None,None,0.740248,0.739584,0,"{222: np.float32(5.518614), 125: np.float32(5....",None,None
238,Neural Network,Imbalanced,Dynamically Generated Hate Speech,None,None,0.730215,0.730152,0,"{19: np.float32(5.4338303), 378: np.float32(5....",None,None
253,Neural Network,SMOTE,Dynamically Generated Hate Speech,None,None,0.736688,0.727254,0,"{7: np.float32(3.827003), 112: np.float32(3.83...",None,None
254,Neural Network,SMOTE,Dynamically Generated Hate Speech,None,None,0.724597,0.724628,0,"{359: np.float32(3.5152912), 259: np.float32(3...",None,None
262,Neural Network,Weighted,Dynamically Generated Hate Speech,None,None,0.727650,0.724477,0,"{201: np.float32(2.97946), 261: np.float32(2.9...",None,None

In [81]:
# Get all classification results for OAA
classification_results[classification_results["Dataset"] == "Online Abusive Attacks"][classification_results["F1-score"] > 0.6].sort_values(by="F1-score", ascending=False)

/tmp/ipython-input-2224288063.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  classification_results[classification_results["Dataset"] == "Online Abusive Attacks"][classification_results["F1-score"] > 0.6].sort_values(by="F1-score", ascending=False)

,Model,Balance,Dataset,Regularizer,Solver,Accuracy,F1-score,Ratio,Feature Importances,Permutation Importances,Best Parameters
169,Neural Network,SMOTE,Online Abusive Attacks,None,None,0.998201,0.998201,0,"{'Toxic parent tweets': np.float32(30.791134),...",None,None
131,K-Nearest Neighbors,SMOTE,Online Abusive Attacks,None,None,0.997302,0.997302,0.0,{'Toxic parent tweets': np.float64(0.724190647...,None,"{'knn_classifier__metric': 'euclidean', 'knn_c..."
122,K-Nearest Neighbors,None,Online Abusive Attacks,None,None,0.993521,0.993524,0.0,{'Toxic parent tweets': np.float64(0.511663066...,None,"{'knn_classifier__metric': 'euclidean', 'knn_c..."
28,Support Vector Machine,Imbalanced,Online Abusive Attacks,None,None,0.984881,0.984983,None,None,"{'Toxic parent tweets': 0.5058315334773218, 'T...",None
82,Decision Tree,Imbalanced,Online Abusive Attacks,None,None,0.974082,0.973596,0.0,{'Toxic parent tweets': np.float64(0.807025867...,None,"{'dt_classifier__min_samples_split': 38, 'dt_c..."
102,Random Forest,imbalanced,Online Abusive Attacks,None,None,0.969762,0.968153,0.0,"{'Toxic parent tweets': 0.8162596519886234, 'T...",None,"{'rf_classifier__n_estimators': 958, 'rf_class..."
112,Random Forest,SMOTE,Online Abusive Attacks,None,None,0.969762,0.968153,0.0,"{'Toxic parent tweets': 0.8162596519886234, 'T...",None,"{'rf_classifier__n_estimators': 958, 'rf_class..."
117,Random Forest,Weighted,Online Abusive Attacks,None,None,0.963283,0.964974,0.0,"{'Toxic parent tweets': 0.7978291606355419, 'T...",None,"{'rf_classifier__n_estimators': 958, 'rf_class..."
97,Decision Tree,Weighted,Online Abusive Attacks,None,None,0.961123,0.962842,0.0,{'Toxic parent tweets': np.float64(0.754169764...,None,"{'dt_classifier__min_samples_split': 38, 'dt_c..."
107,Random Forest,Resampled,Online Abusive Attacks,None,None,0.957734,0.957913,0.0,"{'Toxic parent tweets': 0.7601576998861873, 'T...",None,"{'rf_classifier__n_estimators': 958, 'rf_class..."
92,Decision Tree,SMOTE,Online Abusive Attacks,None,None,0.955036,0.955082,0.0,{'Toxic parent tweets': np.float64(0.729791632...,None,"{'dt_classifier__min_samples_split': 180, 'dt_..."
87,Decision Tree,Resampled,Online Abusive Attacks,None,None,0.935252,0.935062,0.0,{'Toxic parent tweets': np.float64(0.769980772...,None,"{'dt_classifier__min_samples_split': 180, 'dt_..."
12,Logistic Regression,SMOTE,Online Abusive Attacks,l1,saga,0.903777,0.898398,0.0,"{'Toxic replies': -7.789314268739111, 'Toxic p...",None,None
7,Logistic Regression,SMOTE,Online Abusive Attacks,l1,saga,0.903777,0.897601,0.0,"{'index': -0.24873302012164952, 'Toxic replies...",None,None
17,Logistic Regression,Weighted,Online Abusive Attacks,l1,liblinear,0.868251,0.864666,0.0,"{'Toxic replies': -16.193728095652887, 'Toxic ...",None,None
56,Support Vector Machine,SMOTE,Online Abusive Attacks,None,None,0.838416,0.834084,None,None,"{'type': 0.33962221210741916, 'annotator': 0.0...",None
41,Support Vector Machine,SMOTE,Online Abusive Attacks,None,None,0.836848,0.832386,None,None,"{'type': 0.33510806536636795, 'annotator': 0.0...",None
26,Support Vector Machine,Imbalanced,Online Abusive Attacks,None,None,0.827553,0.824574,None,None,"{'type': 0.3356863702979971, 'annotator': 0.0,...",None
71,Support Vector Machine,Weighted,Online Abusive Attacks,None,None,0.827553,0.824574,None,None,"{'type': 0.3356863702979971, 'annotator': 0.0,...",None
57,Support Vector Machine,SMOTE,Online Abusive Attacks,None,None,0.816547,0.814106,None,None,"{'Toxic parent tweets': 0.5973920863309353, 'T...",None
2,Logistic Regression,Imbalanced,Online Abusive Attacks,l1,saga,0.812095,0.800787,0.0,"{'Toxic replies': -6.170820812897218, 'Toxic p...",None,None
72,Support Vector Machine,Weighted,Online Abusive Attacks,None,None,0.755940,0.740535,None,None,"{'Toxic parent tweets': 0.3004319654427646, 'T...",None
156,Gradient Boosting,None,Online Abusive Attacks,None,None,0.758099,0.729504,"{'xgb__learning_rate': np.float64(0.01), 'xgb_...",Weighted,None,"{'Toxic parent tweets': np.float32(1.0), 'Toxi..."
58,Support Vector Machine,SMOTE,Online Abusive Attacks,None,None,0.746403,0.687320,None,None,"{'Toxic parent tweets': 0.4955035971223022, 'T...",None
136,Gradient Boosting,Imbalanced,Online Abusive Attacks,None,None,0.704104,0.641567,"{'gb__learning_rate': np.float64(0.01), 'gb__m...",Imbalanced,None,{'Toxic parent tweets': np.float64(0.925232723...

In [82]:
# Get all classification results for US2020HS
classification_results[classification_results["Dataset"] == "US Elections 2020 Hate Speech"][classification_results["F1-score"] > 0.6].sort_values(by="F1-score", ascending=False)

/tmp/ipython-input-437511567.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  classification_results[classification_results["Dataset"] == "US Elections 2020 Hate Speech"][classification_results["F1-score"] > 0.6].sort_values(by="F1-score", ascending=False)

,Model,Balance,Dataset,Regularizer,Solver,Accuracy,F1-score,Ratio,Feature Importances,Permutation Importances,Best Parameters
29,Support Vector Machine,Imbalanced,US Elections 2020 Hate Speech,None,None,0.883139,0.828334,None,None,"{'Trump': 0.0, 'Biden': 0.0, 'West': 0.0}",None
147,Gradient Boosting,Imbalanced,US Elections 2020 Hate Speech,None,None,0.883139,0.828334,0.0,"{'West': np.float32(0.0), 'Biden': np.float32(...",None,"{'xgb__learning_rate': np.float64(0.01), 'xgb_..."
83,Decision Tree,Imbalanced,US Elections 2020 Hate Speech,None,None,0.883139,0.828334,0.0,"{'Trump': np.float64(0.5835398565902453), 'Bid...",None,"{'dt_classifier__min_samples_split': 72, 'dt_c..."
123,K-Nearest Neighbors,Imbalanced,US Elections 2020 Hate Speech,None,None,0.883139,0.828334,0.0,"{'Trump': np.float64(0.0), 'Biden': np.float64...",None,"{'knn_classifier__metric': 'euclidean', 'knn_c..."
137,Gradient Boosting,Imbalanced,US Elections 2020 Hate Speech,None,None,0.883139,0.828334,0.0,"{'Biden': np.float64(1.0), 'West': np.float64(...",None,"{'gb__learning_rate': 0.01, 'gb__max_depth': 1..."
103,Random Forest,imbalanced,US Elections 2020 Hate Speech,None,None,0.876461,0.818758,0.0,"{'Biden': 0.5341675069108166, 'Trump': 0.46583...",None,"{'rf_classifier__n_estimators': 795, 'rf_class..."
113,Random Forest,SMOTE,US Elections 2020 Hate Speech,None,None,0.876461,0.818758,0.0,"{'Biden': 0.5341675069108166, 'Trump': 0.46583...",None,"{'rf_classifier__n_estimators': 795, 'rf_class..."
31,Support Vector Machine,Imbalanced,US Elections 2020 Hate Speech,None,None,0.776294,0.794436,None,None,"{'Trump': 0.1732888146911519, 'Biden': 0.14574...",None
30,Support Vector Machine,Imbalanced,US Elections 2020 Hate Speech,None,None,0.712855,0.756529,None,None,"{'Trump': 0.045742904841402365, 'Biden': 0.0, ...",None
98,Decision Tree,Weighted,US Elections 2020 Hate Speech,None,None,0.664441,0.724400,0.0,"{'Trump': np.float64(0.6178174351975475), 'Bid...",None,"{'dt_classifier__min_samples_split': 72, 'dt_c..."
118,Random Forest,Weighted,US Elections 2020 Hate Speech,None,None,0.656093,0.714833,0.0,"{'Trump': 0.5298561710641404, 'Biden': 0.47014...",None,"{'rf_classifier__n_estimators': 795, 'rf_class..."
74,Support Vector Machine,Weighted,US Elections 2020 Hate Speech,None,None,0.646077,0.709143,None,None,"{'Biden': 0.12270450751252085, 'Trump': 0.1090...",None
93,Decision Tree,SMOTE,US Elections 2020 Hate Speech,None,None,0.704545,0.703456,0.0,"{'Trump': np.float64(0.5968140469522171), 'Bid...",None,"{'dt_classifier__min_samples_split': 129, 'dt_..."
168,Neural Network,SMOTE,US Elections 2020 Hate Speech,None,None,0.704545,0.703456,0,"{'Trump': np.float32(4.310984), 'Biden': np.fl...",None,None
108,Random Forest,Resampled,US Elections 2020 Hate Speech,None,None,0.703598,0.702632,0.0,"{'Biden': 0.6109033025331421, 'Trump': 0.38909...",None,"{'rf_classifier__n_estimators': 795, 'rf_class..."
132,K-Nearest Neighbors,SMOTE,US Elections 2020 Hate Speech,None,None,0.703598,0.702540,0.0,"{'Trump': np.float64(0.16704545454545455), 'Bi...",None,"{'knn_classifier__metric': 'euclidean', 'knn_c..."
88,Decision Tree,Resampled,US Elections 2020 Hate Speech,None,None,0.688447,0.687829,0.0,"{'Trump': np.float64(0.5584431077275446), 'Bid...",None,"{'dt_classifier__min_samples_split': 129, 'dt_..."
60,Support Vector Machine,SMOTE,US Elections 2020 Hate Speech,None,None,0.673295,0.672976,None,None,"{'Biden': 0.15123106060606065, 'Trump': 0.1204...",None
157,Gradient Boosting,Weighted,US Elections 2020 Hate Speech,None,None,0.601002,0.668059,0.0,"{'Trump': np.float32(1.0), 'West': np.float32(...",None,"{'xgb__learning_rate': np.float64(0.01), 'xgb_..."
46,Support Vector Machine,SMOTE,US Elections 2020 Hate Speech,None,None,0.660985,0.658277,None,None,"{'Trump': 0.13077651515151517, 'Biden': 0.1215...",None
13,Logistic Regression,SMOTE,US Elections 2020 Hate Speech,l1,liblinear,0.648674,0.650330,0.0,"{'West': 0.0, 'Biden': -0.5157701187647922, 'T...",None,None
142,Gradient Boosting,Resampled,US Elections 2020 Hate Speech,None,None,0.649621,0.649299,0.0,"{'Trump': np.float64(0.8192143402998822), 'Bid...",None,"{'gb__learning_rate': np.float64(0.04), 'gb__m..."
45,Support Vector Machine,SMOTE,US Elections 2020 Hate Speech,None,None,0.649621,0.649299,None,None,"{'Trump': 0.10890151515151518, 'Biden': 0.0685...",None
59,Support Vector Machine,SMOTE,US Elections 2020 Hate Speech,None,None,0.648674,0.648666,None,None,"{'Biden': 0.11609848484848484, 'Trump': 0.0739...",None
8,Logistic Regression,SMOTE,US Elections 2020 Hate Speech,l1,liblinear,0.643939,0.643939,0.0,"{'West': 0.0, 'Trump': -0.5361364908316495, 'B...",None,None
44,Support Vector Machine,SMOTE,US Elections 2020 Hate Speech,None,None,0.643939,0.643939,None,None,"{'Biden': 0.11268939393939395, 'Trump': 0.0693...",None
127,K-Nearest Neighbors,Resampled,US Elections 2020 Hate Speech,None,None,0.625000,0.607660,0.0,"{'Biden': np.float64(0.09630681818181819), 'Tr...",None,"{'knn_classifier__metric': 'euclidean', 'knn_c..."

In [83]:
# Get all classification results for MLMA Hate Speech
classification_results[classification_results["Dataset"] == "MLMA Hate Speech"][classification_results["F1-score"] > 0.5][classification_results["Model"] == "Neural Network"].sort_values(by="F1-score", ascending=False)

/tmp/ipython-input-1723158704.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  classification_results[classification_results["Dataset"] == "MLMA Hate Speech"][classification_results["F1-score"] > 0.5][classification_results["Model"] == "Neural Network"].sort_values(by="F1-score", ascending=False)
/tmp/ipython-input-1723158704.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  classification_results[classification_results["Dataset"] == "MLMA Hate Speech"][classification_results["F1-score"] > 0.5][classification_results["Model"] == "Neural Network"].sort_values(by="F1-score", ascending=False)

,Model,Balance,Dataset,Regularizer,Solver,Accuracy,F1-score,Ratio,Feature Importances,Permutation Importances,Best Parameters
255,Neural Network,SMOTE,MLMA Hate Speech,None,None,0.823373,0.814986,0,"{218: np.float32(3.2930164), 347: np.float32(3...",None,None
263,Neural Network,Weighted,MLMA Hate Speech,None,None,0.782205,0.779257,0,"{156: np.float32(6.4274807), 170: np.float32(6...",None,None
239,Neural Network,Imbalanced,MLMA Hate Speech,None,None,0.735281,0.708317,0,"{6: np.float32(5.9408507), 103: np.float32(5.9...",None,None
247,Neural Network,Resample,MLMA Hate Speech,None,None,0.689243,0.646774,0,"{193: np.float32(5.6776276), 129: np.float32(5...",None,None
165,Neural Network,SMOTE,MLMA Hate Speech,None,None,0.574031,0.558313,0,"{'implicit': np.float32(3.3530564), 'explicit'...",None,None
164,Neural Network,Imbalanced,MLMA Hate Speech,None,None,0.608090,0.522185,0,"{'implicit': np.float32(1.7540112), 'explicit'...",None,None
163,Neural Network,Weighted,MLMA Hate Speech,None,None,0.537102,0.504271,0,"{'umap_1': np.float32(1.2173395), 'explicit': ...",None,None

## Compile the Best Results

In [84]:
# Group classification results by dataset and sort by accuracy in descending order
best_accuracy_classification_results = classification_results.groupby("Dataset").apply(lambda x: x.sort_values(["Accuracy"], ascending=False).head(1)).reset_index(drop=True)
best_accuracy_classification_results[["Model", "Balance", "Dataset", "Accuracy", "F1-score"]]

/tmp/ipython-input-3624161802.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  best_accuracy_classification_results = classification_results.groupby("Dataset").apply(lambda x: x.sort_values(["Accuracy"], ascending=False).head(1)).reset_index(drop=True)

,Model,Balance,Dataset,Accuracy,F1-score
0,Neural Network,Imbalanced,Convabuse,0.887122,0.852943
1,Random Forest,Resampled,Dynamically Generated Hate Speech,0.852399,0.851308
2,Neural Network,SMOTE,MLMA Hate Speech,0.823373,0.814986
3,Neural Network,SMOTE,Online Abusive Attacks,0.998201,0.998201
4,Logistic Regression,Imbalanced,US Elections 2020 Hate Speech,0.883139,0.000000

In [85]:
# Group classification results by dataset and sort by f1-score in descending order
best_f1_classification_results = classification_results.groupby("Dataset").apply(lambda x: x.sort_values(["F1-score"], ascending=False).head(1)).reset_index(drop=True)
best_f1_classification_results[["Model", "Balance", "Dataset", "Accuracy", "F1-score"]]

/tmp/ipython-input-4186725504.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  best_f1_classification_results = classification_results.groupby("Dataset").apply(lambda x: x.sort_values(["F1-score"], ascending=False).head(1)).reset_index(drop=True)

,Model,Balance,Dataset,Accuracy,F1-score
0,Logistic Regression,Weighted,Convabuse,0.885533,0.853066
1,Random Forest,Resampled,Dynamically Generated Hate Speech,0.852399,0.851308
2,Neural Network,SMOTE,MLMA Hate Speech,0.823373,0.814986
3,Neural Network,SMOTE,Online Abusive Attacks,0.998201,0.998201
4,Support Vector Machine,Imbalanced,US Elections 2020 Hate Speech,0.883139,0.828334

In [86]:
# Combine indices 0 to 2 from the best_feature_accuracy_classification_results and indices 3 to 4 from the best_feature_f1_classification_results for the best final results
best_final_results = pd.concat([best_accuracy_classification_results.iloc[0:3], best_f1_classification_results.iloc[3:5]]).reset_index(drop=True)
best_final_results = best_final_results[["Model", "Balance", "Dataset", "Accuracy", "F1-score"]]
best_final_results

,Model,Balance,Dataset,Accuracy,F1-score
0,Neural Network,Imbalanced,Convabuse,0.887122,0.852943
1,Random Forest,Resampled,Dynamically Generated Hate Speech,0.852399,0.851308
2,Neural Network,SMOTE,MLMA Hate Speech,0.823373,0.814986
3,Neural Network,SMOTE,Online Abusive Attacks,0.998201,0.998201
4,Support Vector Machine,Imbalanced,US Elections 2020 Hate Speech,0.883139,0.828334

In [87]:
# Group classification results by dataset and sort by accuracy in descending order
best_feature_accuracy_classification_results = feature_classification_results.groupby("Dataset").apply(lambda x: x.sort_values(["Accuracy"], ascending=False).head(1)).reset_index(drop=True)
best_feature_accuracy_classification_results[["Model", "Balance", "Dataset", "Accuracy", "F1-score"]]

/tmp/ipython-input-1321491069.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  best_feature_accuracy_classification_results = feature_classification_results.groupby("Dataset").apply(lambda x: x.sort_values(["Accuracy"], ascending=False).head(1)).reset_index(drop=True)

,Model,Balance,Dataset,Accuracy,F1-score
0,Logistic Regression,Imbalanced,Convabuse,0.885533,0.852027
1,Random Forest,Resampled,Dynamically Generated Hate Speech,0.852399,0.851308
2,Random Forest,imbalanced,MLMA Hate Speech,0.601554,0.511696
3,K-Nearest Neighbors,SMOTE,Online Abusive Attacks,0.997302,0.997302
4,Logistic Regression,Imbalanced,US Elections 2020 Hate Speech,0.883139,0.000000

In [88]:
# Group classification results by dataset and sort by f1-score in descending order
best_feature_f1_classification_results = feature_classification_results.groupby("Dataset").apply(lambda x: x.sort_values(["F1-score"], ascending=False).head(1)).reset_index(drop=True)
best_feature_f1_classification_results[["Model", "Balance", "Dataset", "Accuracy", "F1-score"]]

/tmp/ipython-input-3935630864.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  best_feature_f1_classification_results = feature_classification_results.groupby("Dataset").apply(lambda x: x.sort_values(["F1-score"], ascending=False).head(1)).reset_index(drop=True)

,Model,Balance,Dataset,Accuracy,F1-score
0,Logistic Regression,Weighted,Convabuse,0.885533,0.853066
1,Random Forest,Resampled,Dynamically Generated Hate Speech,0.852399,0.851308
2,K-Nearest Neighbors,Resampled,MLMA Hate Speech,0.529329,0.521837
3,K-Nearest Neighbors,SMOTE,Online Abusive Attacks,0.997302,0.997302
4,Support Vector Machine,Imbalanced,US Elections 2020 Hate Speech,0.883139,0.828334

In [89]:
# Group classification results by dataset and sort by accuracy in descending order
best_embedding_accuracy_classification_results = embedding_classification_results.groupby("Dataset").apply(lambda x: x.sort_values(["Accuracy"], ascending=False).head(1)).reset_index(drop=True)
best_embedding_accuracy_classification_results[["Model", "Balance", "Dataset", "Accuracy", "F1-score"]]

/tmp/ipython-input-1422684289.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  best_embedding_accuracy_classification_results = embedding_classification_results.groupby("Dataset").apply(lambda x: x.sort_values(["Accuracy"], ascending=False).head(1)).reset_index(drop=True)

,Model,Balance,Dataset,Accuracy,F1-score
0,Neural Network,Imbalanced,Convabuse,0.858506,0.828545
1,Neural Network,Resample,Dynamically Generated Hate Speech,0.813785,0.810761
2,Neural Network,SMOTE,MLMA Hate Speech,0.823373,0.814986

In [90]:
# Group classification results by dataset and sort by f1-score in descending order
best_embedding_f1_classification_results = embedding_classification_results.groupby("Dataset").apply(lambda x: x.sort_values(["F1-score"], ascending=False).head(1)).reset_index(drop=True)
best_embedding_f1_classification_results[["Model", "Balance", "Dataset", "Accuracy", "F1-score"]]

/tmp/ipython-input-703808549.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  best_embedding_f1_classification_results = embedding_classification_results.groupby("Dataset").apply(lambda x: x.sort_values(["F1-score"], ascending=False).head(1)).reset_index(drop=True)

,Model,Balance,Dataset,Accuracy,F1-score
0,Neural Network,Imbalanced,Convabuse,0.858506,0.828545
1,Neural Network,Resample,Dynamically Generated Hate Speech,0.813785,0.810761
2,Neural Network,SMOTE,MLMA Hate Speech,0.823373,0.814986

In [91]:
# Group regression results by dataset and sort by R2 in descending order
best_r2_regression_results = regression_results.groupby("Dataset").apply(lambda x: x.sort_values(["R2"], ascending=False).head(1)).reset_index(drop=True)
best_r2_regression_results

/tmp/ipython-input-3350951846.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  best_r2_regression_results = regression_results.groupby("Dataset").apply(lambda x: x.sort_values(["R2"], ascending=False).head(1)).reset_index(drop=True)

,Model,Dataset,Balance,RMSE,R2,Feature Coefficients,Best Parameters
0,Linear Regression,Convabuse,Imbalanced,3.301153e-01,0.891958,"{'system': np.float64(0.48385017824834126), 'e...",None
1,Linear Regression,Dynamically Generated Hate Speech,SMOTE,3.330853e-01,0.556217,"{'original': np.float64(0.10397921440364759), ...",None
2,Linear Regression,MLMA Hate Speech,Resampled,1.023212e+00,0.162586,{'sadness_annotator_sentiment': np.float64(0.1...,None
3,Linear Regression,Online Abusive Attacks,Resampled,3.541690e-13,1.000000,{'High profanity parents': np.float64(22.62607...,None
4,Linear Regression,US Elections 2020 Hate Speech,SMOTE,4.667787e-01,0.128471,"{'West': np.float64(0.0), 'Trump': np.float64(...",None

In [92]:
# Group regression results by dataset and sort by RMSE in ascending order
best_rmse_regression_results = regression_results.groupby("Dataset").apply(lambda x: x.sort_values(["RMSE"], ascending=True).head(1)).reset_index(drop=True)
best_rmse_regression_results

/tmp/ipython-input-1268367184.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  best_rmse_regression_results = regression_results.groupby("Dataset").apply(lambda x: x.sort_values(["RMSE"], ascending=True).head(1)).reset_index(drop=True)

,Model,Dataset,Balance,RMSE,R2,Feature Coefficients,Best Parameters
0,Linear Regression,Convabuse,Imbalanced,3.301153e-01,0.891958,"{'system': np.float64(0.48385017824834126), 'e...",None
1,Linear Regression,Dynamically Generated Hate Speech,SMOTE,3.330853e-01,0.556217,"{'original': np.float64(0.10397921440364759), ...",None
2,Linear Regression,MLMA Hate Speech,Imbalanced,5.689815e-01,0.087107,"{283: np.float32(1.1190851), 181: np.float32(1...",None
3,Linear Regression,Online Abusive Attacks,Resampled,3.541690e-13,1.000000,{'High profanity parents': np.float64(22.62607...,None
4,Linear Regression,US Elections 2020 Hate Speech,Imbalanced,3.107905e-01,0.064087,"{'West': np.float64(0.0), 'Trump': np.float64(...",None

In [93]:
# Group regression results by dataset and sort by silhouette score in descending order
best_silhouette_score_clustering_results = kmeans_clustering.groupby("Dataset").apply(lambda x: x.sort_values(["Chosen Model Silhouette Score"], ascending=False).head(1)).reset_index(drop=True)
best_silhouette_score_clustering_results

/tmp/ipython-input-4155619936.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  best_silhouette_score_clustering_results = kmeans_clustering.groupby("Dataset").apply(lambda x: x.sort_values(["Chosen Model Silhouette Score"], ascending=False).head(1)).reset_index(drop=True)

,Dataset,Best Model Silhouette Score,Best Model Inertia,Chosen Model Silhouette Score,Chosen Model Inertia,Best Parameters,Permutation Importances
0,Convabuse,0.624671,231.569622,0.680004,3.714831e+02,"{'init': 'k-means++', 'max_iter': 1, 'n_init': 1}","{0: array([ 0. , 0. , 9.219..."
1,Dynamically Generated Hate Speech,0.569834,828.591549,0.676209,1.233983e+02,"{'init': 'k-means++', 'max_iter': 2, 'n_init':...","{0: array([ -0.96415169, 20.38557147, 275.651..."
2,MLMA Hate Speech,0.659905,50.600016,0.651497,9.166949e+00,"{'init': 'k-means++', 'max_iter': 3, 'n_init': 6}","{0: array([ 0.41154234, 1.8692177 , 86.273111..."
3,Online Abusive Attacks,0.142857,18.273071,0.346683,1.366048e+01,"{'init': 'k-means++', 'max_iter': 11, 'n_init'...","{0: array([2.85723404, 4.41984288, 5.17479508]..."
4,US Elections 2020 Hate Speech,0.666667,3.879310,0.666667,1.048646e-28,"{'init': 'k-means++', 'max_iter': 1, 'n_init': 1}","{0: array([0. , 3.49137931, 3.49137931]..."

In [94]:
# Group regression results by dataset and sort by inertia in ascending order
best_inertia_clustering_results = kmeans_clustering.groupby("Dataset").apply(lambda x: x.sort_values(["Chosen Model Inertia"], ascending=False).head(1)).reset_index(drop=True)
best_inertia_clustering_results

/tmp/ipython-input-2773436389.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  best_inertia_clustering_results = kmeans_clustering.groupby("Dataset").apply(lambda x: x.sort_values(["Chosen Model Inertia"], ascending=False).head(1)).reset_index(drop=True)

,Dataset,Best Model Silhouette Score,Best Model Inertia,Chosen Model Silhouette Score,Chosen Model Inertia,Best Parameters,Permutation Importances
0,Convabuse,0.624671,231.569622,0.680004,371.483143,"{'init': 'k-means++', 'max_iter': 1, 'n_init': 1}","{0: array([ 0. , 0. , 9.219..."
1,Dynamically Generated Hate Speech,0.605949,973.071098,0.672281,191.073745,"{'init': 'k-means++', 'max_iter': 7, 'n_init': 2}","{0: array([ 3.66216847, 20.3734567 , 391.676..."
2,MLMA Hate Speech,0.197870,1735.592767,0.302355,1208.708738,"{'init': 'k-means++', 'max_iter': 15, 'n_init'...","{0: array([ 2.06499996, 17.19484697, 17.840..."
3,Online Abusive Attacks,0.142857,18.273071,0.346683,13.660480,"{'init': 'k-means++', 'max_iter': 11, 'n_init'...","{0: array([2.85723404, 4.41984288, 5.17479508]..."
4,US Elections 2020 Hate Speech,0.608510,2.744993,0.556711,0.729075,"{'init': 'k-means++', 'max_iter': 1, 'n_init': 3}","{0: array([0. , 2.91904276, 3.76361265]..."

## Output Files

In [95]:
# Output the classification, regression, and clustering results as separate csv files
classification_results.to_csv(f"{results_path}classification_results.csv", index=False)
feature_classification_results.to_csv(f"{results_path}feature_classification_results.csv", index=False)
embedding_classification_results.to_csv(f"{results_path}embedding_classification_results.csv", index=False)
regression_results.to_csv(f"{results_path}regression_results.csv", index=False)
kmeans_clustering.to_csv(f"{results_path}kmeans_clustering_results.csv", index=False)

In [96]:
# Output the best classification, regression, and clustering results as separate csv files
best_accuracy_classification_results.to_csv(f"{results_path}best_accuracy_classification_results.csv", index=False)
best_f1_classification_results.to_csv(f"{results_path}best_f1_classification_results.csv", index=False)
best_r2_regression_results.to_csv(f"{results_path}best_r2_regression_results.csv", index=False)
best_feature_accuracy_classification_results.to_csv(f"{results_path}best_feature_accuracy_classification_results.csv", index=False)
best_feature_f1_classification_results.to_csv(f"{results_path}best_feature_f1_classification_results.csv", index=False)
best_embedding_accuracy_classification_results.to_csv(f"{results_path}best_embedding_accuracy_classification_results.csv", index=False)
best_embedding_f1_classification_results.to_csv(f"{results_path}best_embedding_f1_classification_results.csv", index=False)
best_rmse_regression_results.to_csv(f"{results_path}best_rmse_regression_results.csv", index=False)
best_silhouette_score_clustering_results.to_csv(f"{results_path}best_silhouette_score_clustering_results.csv", index=False)
best_inertia_clustering_results.to_csv(f"{results_path}best_inertia_clustering_results.csv", index=False)